// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hcal_cluster_hls_Find_cluster (
        ap_clk,
        ap_rst,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        hit_dt,
        seed_threshold,
        x,
        y,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [12:0] p_read5;
input  [12:0] p_read6;
input  [12:0] p_read7;
input  [12:0] p_read8;
input  [12:0] p_read9;
input  [12:0] p_read10;
input  [12:0] p_read11;
input  [12:0] p_read12;
input  [2:0] p_read13;
input  [2:0] p_read14;
input  [2:0] p_read15;
input  [2:0] p_read16;
input  [2:0] p_read17;
input  [2:0] p_read18;
input  [2:0] p_read19;
input  [2:0] p_read20;
input  [12:0] p_read21;
input  [12:0] p_read22;
input  [12:0] p_read23;
input  [12:0] p_read24;
input  [12:0] p_read25;
input  [12:0] p_read26;
input  [12:0] p_read27;
input  [12:0] p_read28;
input  [12:0] p_read29;
input  [2:0] p_read30;
input  [2:0] p_read31;
input  [2:0] p_read32;
input  [2:0] p_read33;
input  [2:0] p_read34;
input  [2:0] p_read35;
input  [2:0] p_read36;
input  [2:0] p_read37;
input  [2:0] p_read38;
input  [12:0] p_read39;
input  [12:0] p_read40;
input  [12:0] p_read41;
input  [12:0] p_read42;
input  [12:0] p_read43;
input  [12:0] p_read44;
input  [12:0] p_read45;
input  [12:0] p_read46;
input  [2:0] p_read47;
input  [2:0] p_read48;
input  [2:0] p_read49;
input  [2:0] p_read50;
input  [2:0] p_read51;
input  [2:0] p_read52;
input  [2:0] p_read53;
input  [2:0] p_read54;
input  [2:0] hit_dt;
input  [12:0] seed_threshold;
input  [1:0] x;
input  [3:0] y;
output  [4:0] ap_return_0;
output  [3:0] ap_return_1;
output  [15:0] ap_return_2;
output  [2:0] ap_return_3;
output  [3:0] ap_return_4;
input   ap_ce;

reg[4:0] ap_return_0;
reg[3:0] ap_return_1;
reg[15:0] ap_return_2;
reg[2:0] ap_return_3;
reg[3:0] ap_return_4;

reg   [3:0] y_read_reg_3417;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [3:0] y_read_reg_3417_pp0_iter1_reg;
reg   [1:0] x_read_reg_3422;
reg   [1:0] x_read_reg_3422_pp0_iter1_reg;
reg   [12:0] p_read_8_reg_3427;
reg   [12:0] p_read_8_reg_3427_pp0_iter1_reg;
reg   [12:0] p_read_9_reg_3432;
reg   [12:0] p_read_9_reg_3432_pp0_iter1_reg;
reg   [12:0] p_read_10_reg_3437;
reg   [12:0] p_read_11_reg_3442;
reg   [12:0] p_read_12_reg_3447;
reg   [2:0] p_read_24_reg_3452;
reg   [2:0] p_read_24_reg_3452_pp0_iter1_reg;
reg   [12:0] p_read_25_reg_3457;
reg   [12:0] p_read_25_reg_3457_pp0_iter1_reg;
reg   [12:0] p_read_26_reg_3462;
reg   [12:0] p_read_27_reg_3467;
reg   [12:0] p_read_28_reg_3472;
reg   [12:0] p_read_41_reg_3477;
reg   [12:0] p_read_41_reg_3477_pp0_iter1_reg;
reg   [12:0] p_read_42_reg_3482;
reg   [12:0] p_read1010_reg_3487;
reg   [12:0] p_read99_reg_3492;
reg   [12:0] p_read88_reg_3497;
wire   [0:0] icmp_ln878_fu_458_p2;
reg   [0:0] icmp_ln878_reg_3502;
wire   [0:0] icmp_ln878_reg_3502_pp0_iter0_reg;
reg   [0:0] icmp_ln878_reg_3502_pp0_iter1_reg;
wire   [15:0] select_ln890_15_fu_1660_p3;
reg   [15:0] select_ln890_15_reg_3510;
wire   [0:0] icmp_ln886_26_fu_1668_p2;
reg   [0:0] icmp_ln886_26_reg_3517;
wire   [0:0] and_ln890_19_fu_1724_p2;
reg   [0:0] and_ln890_19_reg_3522;
wire   [0:0] icmp_ln256_3_fu_1756_p2;
reg   [0:0] icmp_ln256_3_reg_3527;
wire   [0:0] and_ln890_21_fu_1814_p2;
reg   [0:0] and_ln890_21_reg_3532;
wire   [0:0] icmp_ln886_27_fu_1850_p2;
reg   [0:0] icmp_ln886_27_reg_3537;
wire   [0:0] and_ln890_23_fu_1910_p2;
reg   [0:0] and_ln890_23_reg_3542;
wire   [0:0] icmp_ln886_28_fu_1944_p2;
reg   [0:0] icmp_ln886_28_reg_3547;
wire   [0:0] and_ln890_25_fu_2000_p2;
reg   [0:0] and_ln890_25_reg_3552;
wire   [0:0] icmp_ln256_4_fu_2032_p2;
reg   [0:0] icmp_ln256_4_reg_3557;
wire   [0:0] and_ln890_27_fu_2090_p2;
reg   [0:0] and_ln890_27_reg_3562;
wire   [0:0] icmp_ln886_29_fu_2126_p2;
reg   [0:0] icmp_ln886_29_reg_3567;
wire   [0:0] and_ln890_29_fu_2186_p2;
reg   [0:0] and_ln890_29_reg_3572;
wire   [0:0] icmp_ln886_30_fu_2220_p2;
reg   [0:0] icmp_ln886_30_reg_3577;
wire   [0:0] and_ln890_31_fu_2276_p2;
reg   [0:0] and_ln890_31_reg_3582;
wire   [0:0] icmp_ln256_5_fu_2308_p2;
reg   [0:0] icmp_ln256_5_reg_3587;
wire   [0:0] and_ln890_33_fu_2366_p2;
reg   [0:0] and_ln890_33_reg_3592;
wire   [0:0] icmp_ln886_31_fu_2402_p2;
reg   [0:0] icmp_ln886_31_reg_3597;
wire   [0:0] and_ln890_35_fu_2462_p2;
reg   [0:0] and_ln890_35_reg_3602;
wire   [0:0] icmp_ln886_32_fu_2496_p2;
reg   [0:0] icmp_ln886_32_reg_3607;
wire   [0:0] and_ln890_37_fu_2552_p2;
reg   [0:0] and_ln890_37_reg_3612;
wire   [0:0] icmp_ln256_6_fu_2584_p2;
reg   [0:0] icmp_ln256_6_reg_3617;
reg   [0:0] icmp_ln256_6_reg_3617_pp0_iter1_reg;
wire   [0:0] and_ln890_39_fu_2642_p2;
reg   [0:0] and_ln890_39_reg_3622;
reg   [0:0] and_ln890_39_reg_3622_pp0_iter1_reg;
wire   [0:0] icmp_ln886_33_fu_2678_p2;
reg   [0:0] icmp_ln886_33_reg_3627;
reg   [0:0] icmp_ln886_33_reg_3627_pp0_iter1_reg;
wire   [0:0] and_ln890_41_fu_2738_p2;
reg   [0:0] and_ln890_41_reg_3632;
reg   [0:0] and_ln890_41_reg_3632_pp0_iter1_reg;
wire   [0:0] icmp_ln886_34_fu_2772_p2;
reg   [0:0] icmp_ln886_34_reg_3637;
reg   [0:0] icmp_ln886_34_reg_3637_pp0_iter1_reg;
wire   [0:0] and_ln890_43_fu_2828_p2;
reg   [0:0] and_ln890_43_reg_3642;
reg   [0:0] and_ln890_43_reg_3642_pp0_iter1_reg;
wire   [0:0] icmp_ln256_7_fu_2860_p2;
reg   [0:0] icmp_ln256_7_reg_3647;
reg   [0:0] icmp_ln256_7_reg_3647_pp0_iter1_reg;
wire   [0:0] and_ln890_45_fu_2918_p2;
reg   [0:0] and_ln890_45_reg_3652;
reg   [0:0] and_ln890_45_reg_3652_pp0_iter1_reg;
wire   [0:0] and_ln890_46_fu_2948_p2;
reg   [0:0] and_ln890_46_reg_3657;
reg   [0:0] and_ln890_46_reg_3657_pp0_iter1_reg;
wire   [3:0] cc_nhits_V_fu_3016_p2;
reg   [3:0] cc_nhits_V_reg_3662;
reg   [3:0] cc_nhits_V_reg_3662_pp0_iter1_reg;
wire   [15:0] select_ln890_32_fu_3242_p3;
reg   [15:0] select_ln890_32_reg_3667;
wire   [3:0] zext_ln213_fu_496_p1;
wire   [3:0] zext_ln208_fu_464_p1;
wire   [0:0] icmp_ln878_1_fu_490_p2;
wire   [3:0] sub_ln213_fu_500_p2;
wire   [3:0] sub_ln213_1_fu_506_p2;
wire   [3:0] select_ln213_fu_512_p3;
wire   [3:0] zext_ln886_fu_480_p1;
wire   [0:0] icmp_ln243_fu_526_p2;
wire   [13:0] zext_ln208_1_fu_538_p1;
wire   [13:0] zext_ln238_fu_468_p1;
wire   [0:0] icmp_ln886_fu_484_p2;
wire   [0:0] icmp_ln890_fu_520_p2;
wire   [0:0] xor_ln886_fu_548_p2;
wire   [0:0] and_ln890_fu_554_p2;
wire   [0:0] xor_ln890_fu_560_p2;
wire   [0:0] xor_ln243_fu_532_p2;
wire   [0:0] or_ln886_fu_570_p2;
wire   [13:0] add_ln208_fu_542_p2;
wire   [13:0] select_ln886_fu_582_p3;
wire   [13:0] select_ln890_fu_590_p3;
wire   [3:0] t1_V_fu_472_p3;
wire   [3:0] zext_ln213_1_fu_608_p1;
wire   [3:0] sub_ln213_8_fu_612_p2;
wire   [0:0] icmp_ln250_fu_624_p2;
wire   [14:0] zext_ln886_2_fu_598_p1;
wire   [14:0] zext_ln208_2_fu_644_p1;
wire   [0:0] icmp_ln886_20_fu_602_p2;
wire   [1:0] zext_ln886_1_fu_566_p1;
wire   [1:0] select_ln213_8_fu_636_p3;
wire   [0:0] icmp_ln890_1_fu_618_p2;
wire   [0:0] xor_ln886_1_fu_662_p2;
wire   [0:0] and_ln890_1_fu_668_p2;
wire   [1:0] select_ln886_1_fu_654_p3;
wire   [0:0] xor_ln250_fu_630_p2;
wire   [0:0] or_ln886_1_fu_682_p2;
wire   [0:0] or_ln890_fu_576_p2;
wire   [0:0] or_ln890_1_fu_688_p2;
wire   [14:0] add_ln208_1_fu_648_p2;
wire   [14:0] select_ln886_2_fu_700_p3;
wire   [3:0] or_ln_fu_722_p3;
wire   [3:0] sub_ln213_9_fu_730_p2;
wire   [0:0] icmp_ln257_fu_742_p2;
wire   [1:0] select_ln890_1_fu_674_p3;
wire   [14:0] select_ln890_2_fu_708_p3;
wire   [14:0] zext_ln208_24_fu_760_p1;
wire   [0:0] icmp_ln256_fu_716_p2;
wire   [1:0] add_ln213_fu_754_p2;
wire   [0:0] icmp_ln890_2_fu_736_p2;
wire   [0:0] xor_ln256_fu_778_p2;
wire   [0:0] and_ln890_3_fu_784_p2;
wire   [1:0] select_ln256_fu_770_p3;
wire   [1:0] select_ln890_3_fu_790_p3;
wire   [0:0] xor_ln257_fu_748_p2;
wire   [0:0] or_ln256_fu_802_p2;
wire   [0:0] and_ln890_2_fu_694_p2;
wire   [0:0] or_ln890_2_fu_808_p2;
wire   [14:0] add_ln208_2_fu_764_p2;
wire   [14:0] select_ln256_1_fu_820_p3;
wire   [14:0] select_ln890_4_fu_828_p3;
wire   [3:0] zext_ln213_2_fu_852_p1;
wire   [0:0] icmp_ln878_2_fu_846_p2;
wire   [3:0] sub_ln213_10_fu_856_p2;
wire   [3:0] sub_ln213_11_fu_862_p2;
wire   [3:0] select_ln213_1_fu_868_p3;
wire   [0:0] icmp_ln243_1_fu_882_p2;
wire   [15:0] zext_ln886_3_fu_836_p1;
wire   [15:0] zext_ln208_8_fu_894_p1;
wire   [0:0] icmp_ln886_21_fu_840_p2;
wire   [0:0] icmp_ln890_8_fu_876_p2;
wire   [0:0] xor_ln886_2_fu_904_p2;
wire   [0:0] and_ln890_5_fu_910_p2;
wire   [0:0] xor_ln890_1_fu_916_p2;
wire   [0:0] xor_ln243_1_fu_888_p2;
wire   [0:0] or_ln886_2_fu_926_p2;
wire   [0:0] and_ln890_4_fu_814_p2;
wire   [0:0] or_ln890_3_fu_932_p2;
wire   [15:0] add_ln208_3_fu_898_p2;
wire   [15:0] select_ln886_3_fu_944_p3;
wire   [3:0] zext_ln213_8_fu_966_p1;
wire   [3:0] sub_ln213_12_fu_970_p2;
wire   [0:0] icmp_ln250_1_fu_982_p2;
wire   [15:0] select_ln890_5_fu_952_p3;
wire   [15:0] zext_ln208_9_fu_1002_p1;
wire   [0:0] icmp_ln886_22_fu_960_p2;
wire   [1:0] zext_ln886_4_fu_922_p1;
wire   [1:0] select_ln213_9_fu_994_p3;
wire   [0:0] icmp_ln890_9_fu_976_p2;
wire   [0:0] xor_ln886_3_fu_1020_p2;
wire   [0:0] and_ln890_7_fu_1026_p2;
wire   [1:0] select_ln886_4_fu_1012_p3;
wire   [0:0] xor_ln250_1_fu_988_p2;
wire   [0:0] or_ln886_3_fu_1040_p2;
wire   [0:0] and_ln890_6_fu_938_p2;
wire   [0:0] or_ln890_4_fu_1046_p2;
wire   [15:0] add_ln208_4_fu_1006_p2;
wire   [15:0] select_ln886_5_fu_1058_p3;
wire   [3:0] or_ln213_1_fu_1080_p3;
wire   [3:0] sub_ln213_13_fu_1088_p2;
wire   [0:0] icmp_ln257_1_fu_1100_p2;
wire   [1:0] select_ln890_6_fu_1032_p3;
wire   [15:0] select_ln890_7_fu_1066_p3;
wire   [15:0] zext_ln208_10_fu_1118_p1;
wire   [0:0] icmp_ln256_1_fu_1074_p2;
wire   [1:0] add_ln213_1_fu_1112_p2;
wire   [0:0] icmp_ln890_10_fu_1094_p2;
wire   [0:0] xor_ln256_1_fu_1136_p2;
wire   [0:0] and_ln890_9_fu_1142_p2;
wire   [1:0] select_ln256_2_fu_1128_p3;
wire   [1:0] select_ln890_8_fu_1148_p3;
wire   [0:0] xor_ln257_1_fu_1106_p2;
wire   [0:0] or_ln256_1_fu_1160_p2;
wire   [0:0] and_ln890_8_fu_1052_p2;
wire   [0:0] or_ln890_5_fu_1166_p2;
wire   [15:0] add_ln208_5_fu_1122_p2;
wire   [15:0] select_ln256_3_fu_1178_p3;
wire   [3:0] zext_ln213_9_fu_1206_p1;
wire   [0:0] icmp_ln878_3_fu_1200_p2;
wire   [3:0] sub_ln213_2_fu_1210_p2;
wire   [3:0] sub_ln213_14_fu_1216_p2;
wire   [3:0] select_ln213_2_fu_1222_p3;
wire   [0:0] icmp_ln243_2_fu_1236_p2;
wire   [15:0] select_ln890_9_fu_1186_p3;
wire   [15:0] zext_ln208_11_fu_1248_p1;
wire   [0:0] icmp_ln886_23_fu_1194_p2;
wire   [0:0] icmp_ln890_11_fu_1230_p2;
wire   [0:0] xor_ln886_4_fu_1258_p2;
wire   [0:0] and_ln890_11_fu_1264_p2;
wire   [0:0] xor_ln890_2_fu_1270_p2;
wire   [0:0] xor_ln243_2_fu_1242_p2;
wire   [0:0] or_ln886_4_fu_1280_p2;
wire   [0:0] and_ln890_10_fu_1172_p2;
wire   [0:0] or_ln890_6_fu_1286_p2;
wire   [15:0] add_ln208_6_fu_1252_p2;
wire   [15:0] select_ln886_6_fu_1298_p3;
wire   [3:0] zext_ln213_10_fu_1320_p1;
wire   [3:0] sub_ln213_15_fu_1324_p2;
wire   [0:0] icmp_ln250_2_fu_1336_p2;
wire   [15:0] select_ln890_10_fu_1306_p3;
wire   [15:0] zext_ln208_12_fu_1356_p1;
wire   [0:0] icmp_ln886_24_fu_1314_p2;
wire   [1:0] zext_ln886_5_fu_1276_p1;
wire   [1:0] select_ln213_10_fu_1348_p3;
wire   [0:0] icmp_ln890_12_fu_1330_p2;
wire   [0:0] xor_ln886_5_fu_1374_p2;
wire   [0:0] and_ln890_13_fu_1380_p2;
wire   [1:0] select_ln886_7_fu_1366_p3;
wire   [0:0] xor_ln250_2_fu_1342_p2;
wire   [0:0] or_ln886_5_fu_1394_p2;
wire   [0:0] and_ln890_12_fu_1292_p2;
wire   [0:0] or_ln890_7_fu_1400_p2;
wire   [15:0] add_ln208_7_fu_1360_p2;
wire   [15:0] select_ln886_8_fu_1412_p3;
wire   [3:0] or_ln213_2_fu_1434_p3;
wire   [3:0] sub_ln213_16_fu_1442_p2;
wire   [0:0] icmp_ln257_2_fu_1454_p2;
wire   [1:0] select_ln890_11_fu_1386_p3;
wire   [15:0] select_ln890_12_fu_1420_p3;
wire   [15:0] zext_ln208_13_fu_1472_p1;
wire   [0:0] icmp_ln256_2_fu_1428_p2;
wire   [1:0] add_ln213_2_fu_1466_p2;
wire   [0:0] icmp_ln890_13_fu_1448_p2;
wire   [0:0] xor_ln256_2_fu_1490_p2;
wire   [0:0] and_ln890_15_fu_1496_p2;
wire   [1:0] select_ln256_4_fu_1482_p3;
wire   [1:0] select_ln890_13_fu_1502_p3;
wire   [0:0] xor_ln257_2_fu_1460_p2;
wire   [0:0] or_ln256_2_fu_1514_p2;
wire   [0:0] and_ln890_14_fu_1406_p2;
wire   [0:0] or_ln890_8_fu_1520_p2;
wire   [15:0] add_ln208_8_fu_1476_p2;
wire   [15:0] select_ln256_5_fu_1532_p3;
wire   [3:0] zext_ln213_3_fu_1560_p1;
wire   [0:0] icmp_ln878_4_fu_1554_p2;
wire   [3:0] sub_ln213_3_fu_1564_p2;
wire   [3:0] sub_ln213_17_fu_1570_p2;
wire   [3:0] select_ln213_3_fu_1576_p3;
wire   [0:0] icmp_ln243_3_fu_1590_p2;
wire   [15:0] select_ln890_14_fu_1540_p3;
wire   [15:0] zext_ln208_3_fu_1602_p1;
wire   [0:0] icmp_ln886_25_fu_1548_p2;
wire   [0:0] icmp_ln890_3_fu_1584_p2;
wire   [0:0] xor_ln886_6_fu_1612_p2;
wire   [0:0] and_ln890_17_fu_1618_p2;
wire   [0:0] xor_ln890_3_fu_1624_p2;
wire   [0:0] xor_ln243_3_fu_1596_p2;
wire   [0:0] or_ln886_6_fu_1634_p2;
wire   [0:0] and_ln890_16_fu_1526_p2;
wire   [0:0] or_ln890_9_fu_1640_p2;
wire   [15:0] add_ln208_9_fu_1606_p2;
wire   [15:0] select_ln886_9_fu_1652_p3;
wire   [3:0] zext_ln213_11_fu_1674_p1;
wire   [3:0] sub_ln213_18_fu_1678_p2;
wire   [0:0] icmp_ln250_3_fu_1690_p2;
wire   [1:0] zext_ln886_6_fu_1630_p1;
wire   [1:0] select_ln213_11_fu_1702_p3;
wire   [0:0] icmp_ln890_14_fu_1684_p2;
wire   [0:0] xor_ln886_7_fu_1718_p2;
wire   [1:0] select_ln886_10_fu_1710_p3;
wire   [0:0] xor_ln250_3_fu_1696_p2;
wire   [0:0] or_ln886_7_fu_1738_p2;
wire   [0:0] and_ln890_18_fu_1646_p2;
wire   [0:0] or_ln890_10_fu_1744_p2;
wire   [3:0] or_ln213_3_fu_1762_p3;
wire   [3:0] sub_ln213_19_fu_1770_p2;
wire   [0:0] icmp_ln257_3_fu_1782_p2;
wire   [1:0] select_ln890_16_fu_1730_p3;
wire   [1:0] add_ln213_3_fu_1794_p2;
wire   [0:0] icmp_ln890_15_fu_1776_p2;
wire   [0:0] xor_ln256_3_fu_1808_p2;
wire   [1:0] select_ln256_6_fu_1800_p3;
wire   [1:0] select_ln890_18_fu_1820_p3;
wire   [0:0] xor_ln257_3_fu_1788_p2;
wire   [0:0] or_ln256_3_fu_1832_p2;
wire   [0:0] and_ln890_20_fu_1750_p2;
wire   [0:0] or_ln890_11_fu_1838_p2;
wire   [3:0] zext_ln213_4_fu_1862_p1;
wire   [0:0] icmp_ln878_5_fu_1856_p2;
wire   [3:0] sub_ln213_4_fu_1866_p2;
wire   [3:0] sub_ln213_20_fu_1872_p2;
wire   [3:0] select_ln213_4_fu_1878_p3;
wire   [0:0] icmp_ln243_4_fu_1892_p2;
wire   [0:0] icmp_ln890_4_fu_1886_p2;
wire   [0:0] xor_ln886_8_fu_1904_p2;
wire   [0:0] xor_ln890_4_fu_1916_p2;
wire   [0:0] xor_ln243_4_fu_1898_p2;
wire   [0:0] or_ln886_8_fu_1926_p2;
wire   [0:0] and_ln890_22_fu_1844_p2;
wire   [0:0] or_ln890_12_fu_1932_p2;
wire   [3:0] zext_ln213_12_fu_1950_p1;
wire   [3:0] sub_ln213_21_fu_1954_p2;
wire   [0:0] icmp_ln250_4_fu_1966_p2;
wire   [1:0] zext_ln886_7_fu_1922_p1;
wire   [1:0] select_ln213_12_fu_1978_p3;
wire   [0:0] icmp_ln890_16_fu_1960_p2;
wire   [0:0] xor_ln886_9_fu_1994_p2;
wire   [1:0] select_ln886_13_fu_1986_p3;
wire   [0:0] xor_ln250_4_fu_1972_p2;
wire   [0:0] or_ln886_9_fu_2014_p2;
wire   [0:0] and_ln890_24_fu_1938_p2;
wire   [0:0] or_ln890_13_fu_2020_p2;
wire   [3:0] or_ln213_4_fu_2038_p3;
wire   [3:0] sub_ln213_22_fu_2046_p2;
wire   [0:0] icmp_ln257_4_fu_2058_p2;
wire   [1:0] select_ln890_21_fu_2006_p3;
wire   [1:0] add_ln213_4_fu_2070_p2;
wire   [0:0] icmp_ln890_17_fu_2052_p2;
wire   [0:0] xor_ln256_4_fu_2084_p2;
wire   [1:0] select_ln256_8_fu_2076_p3;
wire   [1:0] select_ln890_23_fu_2096_p3;
wire   [0:0] xor_ln257_4_fu_2064_p2;
wire   [0:0] or_ln256_4_fu_2108_p2;
wire   [0:0] and_ln890_26_fu_2026_p2;
wire   [0:0] or_ln890_14_fu_2114_p2;
wire   [3:0] zext_ln213_5_fu_2138_p1;
wire   [0:0] icmp_ln878_6_fu_2132_p2;
wire   [3:0] sub_ln213_5_fu_2142_p2;
wire   [3:0] sub_ln213_23_fu_2148_p2;
wire   [3:0] select_ln213_5_fu_2154_p3;
wire   [0:0] icmp_ln243_5_fu_2168_p2;
wire   [0:0] icmp_ln890_5_fu_2162_p2;
wire   [0:0] xor_ln886_10_fu_2180_p2;
wire   [0:0] xor_ln890_5_fu_2192_p2;
wire   [0:0] xor_ln243_5_fu_2174_p2;
wire   [0:0] or_ln886_10_fu_2202_p2;
wire   [0:0] and_ln890_28_fu_2120_p2;
wire   [0:0] or_ln890_15_fu_2208_p2;
wire   [3:0] zext_ln213_13_fu_2226_p1;
wire   [3:0] sub_ln213_24_fu_2230_p2;
wire   [0:0] icmp_ln250_5_fu_2242_p2;
wire   [1:0] zext_ln886_8_fu_2198_p1;
wire   [1:0] select_ln213_13_fu_2254_p3;
wire   [0:0] icmp_ln890_18_fu_2236_p2;
wire   [0:0] xor_ln886_11_fu_2270_p2;
wire   [1:0] select_ln886_16_fu_2262_p3;
wire   [0:0] xor_ln250_5_fu_2248_p2;
wire   [0:0] or_ln886_11_fu_2290_p2;
wire   [0:0] and_ln890_30_fu_2214_p2;
wire   [0:0] or_ln890_16_fu_2296_p2;
wire   [3:0] or_ln213_5_fu_2314_p3;
wire   [3:0] sub_ln213_25_fu_2322_p2;
wire   [0:0] icmp_ln257_5_fu_2334_p2;
wire   [1:0] select_ln890_26_fu_2282_p3;
wire   [1:0] add_ln213_5_fu_2346_p2;
wire   [0:0] icmp_ln890_19_fu_2328_p2;
wire   [0:0] xor_ln256_5_fu_2360_p2;
wire   [1:0] select_ln256_10_fu_2352_p3;
wire   [1:0] select_ln890_28_fu_2372_p3;
wire   [0:0] xor_ln257_5_fu_2340_p2;
wire   [0:0] or_ln256_5_fu_2384_p2;
wire   [0:0] and_ln890_32_fu_2302_p2;
wire   [0:0] or_ln890_17_fu_2390_p2;
wire   [3:0] zext_ln213_6_fu_2414_p1;
wire   [0:0] icmp_ln878_7_fu_2408_p2;
wire   [3:0] sub_ln213_6_fu_2418_p2;
wire   [3:0] sub_ln213_26_fu_2424_p2;
wire   [3:0] select_ln213_6_fu_2430_p3;
wire   [0:0] icmp_ln243_6_fu_2444_p2;
wire   [0:0] icmp_ln890_6_fu_2438_p2;
wire   [0:0] xor_ln886_12_fu_2456_p2;
wire   [0:0] xor_ln890_6_fu_2468_p2;
wire   [0:0] xor_ln243_6_fu_2450_p2;
wire   [0:0] or_ln886_12_fu_2478_p2;
wire   [0:0] and_ln890_34_fu_2396_p2;
wire   [0:0] or_ln890_18_fu_2484_p2;
wire   [3:0] zext_ln213_14_fu_2502_p1;
wire   [3:0] sub_ln213_27_fu_2506_p2;
wire   [0:0] icmp_ln250_6_fu_2518_p2;
wire   [1:0] zext_ln886_9_fu_2474_p1;
wire   [1:0] select_ln213_14_fu_2530_p3;
wire   [0:0] icmp_ln890_20_fu_2512_p2;
wire   [0:0] xor_ln886_13_fu_2546_p2;
wire   [1:0] select_ln886_19_fu_2538_p3;
wire   [0:0] xor_ln250_6_fu_2524_p2;
wire   [0:0] or_ln886_13_fu_2566_p2;
wire   [0:0] and_ln890_36_fu_2490_p2;
wire   [0:0] or_ln890_19_fu_2572_p2;
wire   [3:0] or_ln213_6_fu_2590_p3;
wire   [3:0] sub_ln213_28_fu_2598_p2;
wire   [0:0] icmp_ln257_6_fu_2610_p2;
wire   [1:0] select_ln890_31_fu_2558_p3;
wire   [1:0] add_ln213_6_fu_2622_p2;
wire   [0:0] icmp_ln890_21_fu_2604_p2;
wire   [0:0] xor_ln256_6_fu_2636_p2;
wire   [1:0] select_ln256_12_fu_2628_p3;
wire   [1:0] select_ln890_33_fu_2648_p3;
wire   [0:0] xor_ln257_6_fu_2616_p2;
wire   [0:0] or_ln256_6_fu_2660_p2;
wire   [0:0] and_ln890_38_fu_2578_p2;
wire   [0:0] or_ln890_20_fu_2666_p2;
wire   [3:0] zext_ln213_7_fu_2690_p1;
wire   [0:0] icmp_ln878_8_fu_2684_p2;
wire   [3:0] sub_ln213_7_fu_2694_p2;
wire   [3:0] sub_ln213_29_fu_2700_p2;
wire   [3:0] select_ln213_7_fu_2706_p3;
wire   [0:0] icmp_ln243_7_fu_2720_p2;
wire   [0:0] icmp_ln890_7_fu_2714_p2;
wire   [0:0] xor_ln886_14_fu_2732_p2;
wire   [0:0] xor_ln890_7_fu_2744_p2;
wire   [0:0] xor_ln243_7_fu_2726_p2;
wire   [0:0] or_ln886_14_fu_2754_p2;
wire   [0:0] and_ln890_40_fu_2672_p2;
wire   [0:0] or_ln890_21_fu_2760_p2;
wire   [3:0] zext_ln213_15_fu_2778_p1;
wire   [3:0] sub_ln213_30_fu_2782_p2;
wire   [0:0] icmp_ln250_7_fu_2794_p2;
wire   [1:0] zext_ln886_10_fu_2750_p1;
wire   [1:0] select_ln213_15_fu_2806_p3;
wire   [0:0] icmp_ln890_22_fu_2788_p2;
wire   [0:0] xor_ln886_15_fu_2822_p2;
wire   [1:0] select_ln886_22_fu_2814_p3;
wire   [0:0] xor_ln250_7_fu_2800_p2;
wire   [0:0] or_ln886_15_fu_2842_p2;
wire   [0:0] and_ln890_42_fu_2766_p2;
wire   [0:0] or_ln890_22_fu_2848_p2;
wire   [3:0] or_ln213_7_fu_2866_p3;
wire   [3:0] sub_ln213_31_fu_2874_p2;
wire   [0:0] icmp_ln257_7_fu_2886_p2;
wire   [1:0] select_ln890_36_fu_2834_p3;
wire   [1:0] add_ln213_7_fu_2898_p2;
wire   [0:0] icmp_ln890_23_fu_2880_p2;
wire   [0:0] xor_ln256_7_fu_2912_p2;
wire   [1:0] select_ln256_14_fu_2904_p3;
wire   [1:0] select_ln890_38_fu_2924_p3;
wire   [0:0] xor_ln257_7_fu_2892_p2;
wire   [0:0] or_ln256_7_fu_2936_p2;
wire   [0:0] and_ln890_44_fu_2854_p2;
wire   [0:0] or_ln890_23_fu_2942_p2;
wire   [2:0] zext_ln256_fu_798_p1;
wire   [2:0] zext_ln256_8_fu_2954_p1;
wire   [2:0] add_ln208_24_fu_2958_p2;
wire   [2:0] zext_ln256_1_fu_1156_p1;
wire   [2:0] zext_ln256_2_fu_1510_p1;
wire   [2:0] add_ln208_25_fu_2968_p2;
wire   [3:0] zext_ln208_26_fu_2974_p1;
wire   [3:0] zext_ln208_25_fu_2964_p1;
wire   [2:0] zext_ln256_3_fu_1828_p1;
wire   [2:0] zext_ln256_4_fu_2104_p1;
wire   [2:0] add_ln208_27_fu_2984_p2;
wire   [2:0] zext_ln256_6_fu_2656_p1;
wire   [2:0] zext_ln256_7_fu_2932_p1;
wire   [2:0] add_ln208_28_fu_2994_p2;
wire   [3:0] zext_ln208_28_fu_3000_p1;
wire   [3:0] zext_ln256_5_fu_2380_p1;
wire   [3:0] add_ln208_29_fu_3004_p2;
wire   [3:0] zext_ln208_27_fu_2990_p1;
wire   [3:0] add_ln208_30_fu_3010_p2;
wire   [3:0] add_ln208_26_fu_2978_p2;
wire   [15:0] zext_ln208_14_fu_3022_p1;
wire   [15:0] add_ln208_10_fu_3025_p2;
wire   [15:0] select_ln886_11_fu_3030_p3;
wire   [15:0] select_ln890_17_fu_3036_p3;
wire   [15:0] zext_ln208_15_fu_3042_p1;
wire   [15:0] add_ln208_11_fu_3045_p2;
wire   [15:0] select_ln256_7_fu_3051_p3;
wire   [15:0] select_ln890_19_fu_3058_p3;
wire   [15:0] zext_ln208_4_fu_3065_p1;
wire   [15:0] add_ln208_12_fu_3068_p2;
wire   [15:0] select_ln886_12_fu_3074_p3;
wire   [15:0] select_ln890_20_fu_3081_p3;
wire   [15:0] zext_ln208_16_fu_3088_p1;
wire   [15:0] add_ln208_13_fu_3091_p2;
wire   [15:0] select_ln886_14_fu_3097_p3;
wire   [15:0] select_ln890_22_fu_3104_p3;
wire   [15:0] zext_ln208_17_fu_3111_p1;
wire   [15:0] add_ln208_14_fu_3114_p2;
wire   [15:0] select_ln256_9_fu_3120_p3;
wire   [15:0] select_ln890_24_fu_3127_p3;
wire   [15:0] zext_ln208_5_fu_3134_p1;
wire   [15:0] add_ln208_15_fu_3137_p2;
wire   [15:0] select_ln886_15_fu_3143_p3;
wire   [15:0] select_ln890_25_fu_3150_p3;
wire   [15:0] zext_ln208_18_fu_3157_p1;
wire   [15:0] add_ln208_16_fu_3160_p2;
wire   [15:0] select_ln886_17_fu_3166_p3;
wire   [15:0] select_ln890_27_fu_3173_p3;
wire   [15:0] zext_ln208_19_fu_3180_p1;
wire   [15:0] add_ln208_17_fu_3183_p2;
wire   [15:0] select_ln256_11_fu_3189_p3;
wire   [15:0] select_ln890_29_fu_3196_p3;
wire   [15:0] zext_ln208_6_fu_3203_p1;
wire   [15:0] add_ln208_18_fu_3206_p2;
wire   [15:0] select_ln886_18_fu_3212_p3;
wire   [15:0] select_ln890_30_fu_3219_p3;
wire   [15:0] zext_ln208_20_fu_3226_p1;
wire   [15:0] add_ln208_19_fu_3229_p2;
wire   [15:0] select_ln886_20_fu_3235_p3;
wire   [15:0] zext_ln208_21_fu_3252_p1;
wire   [15:0] add_ln208_20_fu_3255_p2;
wire   [15:0] select_ln256_13_fu_3260_p3;
wire   [15:0] select_ln890_34_fu_3266_p3;
wire   [15:0] zext_ln208_7_fu_3272_p1;
wire   [15:0] add_ln208_21_fu_3275_p2;
wire   [15:0] select_ln886_21_fu_3281_p3;
wire   [15:0] select_ln890_35_fu_3288_p3;
wire   [15:0] zext_ln208_22_fu_3295_p1;
wire   [15:0] add_ln208_22_fu_3298_p2;
wire   [15:0] select_ln886_23_fu_3304_p3;
wire   [15:0] select_ln890_37_fu_3311_p3;
wire   [15:0] zext_ln208_23_fu_3318_p1;
wire   [15:0] add_ln208_23_fu_3321_p2;
wire   [15:0] select_ln256_15_fu_3327_p3;
wire   [15:0] select_ln890_39_fu_3334_p3;
wire   [0:0] or_ln886_16_fu_3348_p2;
wire   [15:0] select_ln878_fu_3341_p3;
wire   [2:0] select_ln878_1_fu_3360_p3;
wire   [3:0] select_ln878_2_fu_3374_p3;
wire   [4:0] x_cast_fu_3249_p1;
wire   [15:0] select_ln886_24_fu_3352_p3;
wire   [2:0] select_ln886_25_fu_3366_p3;
wire   [3:0] select_ln886_26_fu_3380_p3;
reg    ap_ce_reg;
reg   [12:0] p_read5_int_reg;
reg   [12:0] p_read6_int_reg;
reg   [12:0] p_read7_int_reg;
reg   [12:0] p_read8_int_reg;
reg   [12:0] p_read9_int_reg;
reg   [12:0] p_read10_int_reg;
reg   [12:0] p_read11_int_reg;
reg   [12:0] p_read12_int_reg;
reg   [2:0] p_read13_int_reg;
reg   [2:0] p_read14_int_reg;
reg   [2:0] p_read15_int_reg;
reg   [2:0] p_read16_int_reg;
reg   [2:0] p_read17_int_reg;
reg   [2:0] p_read18_int_reg;
reg   [2:0] p_read19_int_reg;
reg   [2:0] p_read20_int_reg;
reg   [12:0] p_read21_int_reg;
reg   [12:0] p_read22_int_reg;
reg   [12:0] p_read23_int_reg;
reg   [12:0] p_read24_int_reg;
reg   [12:0] p_read25_int_reg;
reg   [12:0] p_read26_int_reg;
reg   [12:0] p_read27_int_reg;
reg   [12:0] p_read28_int_reg;
reg   [12:0] p_read29_int_reg;
reg   [2:0] p_read30_int_reg;
reg   [2:0] p_read31_int_reg;
reg   [2:0] p_read32_int_reg;
reg   [2:0] p_read33_int_reg;
reg   [2:0] p_read34_int_reg;
reg   [2:0] p_read35_int_reg;
reg   [2:0] p_read36_int_reg;
reg   [2:0] p_read37_int_reg;
reg   [2:0] p_read38_int_reg;
reg   [12:0] p_read39_int_reg;
reg   [12:0] p_read40_int_reg;
reg   [12:0] p_read41_int_reg;
reg   [12:0] p_read42_int_reg;
reg   [12:0] p_read43_int_reg;
reg   [12:0] p_read44_int_reg;
reg   [12:0] p_read45_int_reg;
reg   [12:0] p_read46_int_reg;
reg   [2:0] p_read47_int_reg;
reg   [2:0] p_read48_int_reg;
reg   [2:0] p_read49_int_reg;
reg   [2:0] p_read50_int_reg;
reg   [2:0] p_read51_int_reg;
reg   [2:0] p_read52_int_reg;
reg   [2:0] p_read53_int_reg;
reg   [2:0] p_read54_int_reg;
reg   [2:0] hit_dt_int_reg;
reg   [12:0] seed_threshold_int_reg;
reg   [1:0] x_int_reg;
reg   [3:0] y_int_reg;
reg   [4:0] ap_return_0_int_reg;
reg   [3:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [2:0] ap_return_3_int_reg;
reg   [3:0] ap_return_4_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        and_ln890_19_reg_3522 <= and_ln890_19_fu_1724_p2;
        and_ln890_21_reg_3532 <= and_ln890_21_fu_1814_p2;
        and_ln890_23_reg_3542 <= and_ln890_23_fu_1910_p2;
        and_ln890_25_reg_3552 <= and_ln890_25_fu_2000_p2;
        and_ln890_27_reg_3562 <= and_ln890_27_fu_2090_p2;
        and_ln890_29_reg_3572 <= and_ln890_29_fu_2186_p2;
        and_ln890_31_reg_3582 <= and_ln890_31_fu_2276_p2;
        and_ln890_33_reg_3592 <= and_ln890_33_fu_2366_p2;
        and_ln890_35_reg_3602 <= and_ln890_35_fu_2462_p2;
        and_ln890_37_reg_3612 <= and_ln890_37_fu_2552_p2;
        and_ln890_39_reg_3622 <= and_ln890_39_fu_2642_p2;
        and_ln890_39_reg_3622_pp0_iter1_reg <= and_ln890_39_reg_3622;
        and_ln890_41_reg_3632 <= and_ln890_41_fu_2738_p2;
        and_ln890_41_reg_3632_pp0_iter1_reg <= and_ln890_41_reg_3632;
        and_ln890_43_reg_3642 <= and_ln890_43_fu_2828_p2;
        and_ln890_43_reg_3642_pp0_iter1_reg <= and_ln890_43_reg_3642;
        and_ln890_45_reg_3652 <= and_ln890_45_fu_2918_p2;
        and_ln890_45_reg_3652_pp0_iter1_reg <= and_ln890_45_reg_3652;
        and_ln890_46_reg_3657 <= and_ln890_46_fu_2948_p2;
        and_ln890_46_reg_3657_pp0_iter1_reg <= and_ln890_46_reg_3657;
        ap_return_0_int_reg[1 : 0] <= x_cast_fu_3249_p1[1 : 0];
        ap_return_1_int_reg <= y_read_reg_3417_pp0_iter1_reg;
        ap_return_2_int_reg <= select_ln886_24_fu_3352_p3;
        ap_return_3_int_reg <= select_ln886_25_fu_3366_p3;
        ap_return_4_int_reg <= select_ln886_26_fu_3380_p3;
        cc_nhits_V_reg_3662 <= cc_nhits_V_fu_3016_p2;
        cc_nhits_V_reg_3662_pp0_iter1_reg <= cc_nhits_V_reg_3662;
        icmp_ln256_3_reg_3527 <= icmp_ln256_3_fu_1756_p2;
        icmp_ln256_4_reg_3557 <= icmp_ln256_4_fu_2032_p2;
        icmp_ln256_5_reg_3587 <= icmp_ln256_5_fu_2308_p2;
        icmp_ln256_6_reg_3617 <= icmp_ln256_6_fu_2584_p2;
        icmp_ln256_6_reg_3617_pp0_iter1_reg <= icmp_ln256_6_reg_3617;
        icmp_ln256_7_reg_3647 <= icmp_ln256_7_fu_2860_p2;
        icmp_ln256_7_reg_3647_pp0_iter1_reg <= icmp_ln256_7_reg_3647;
        icmp_ln878_reg_3502 <= icmp_ln878_fu_458_p2;
        icmp_ln878_reg_3502_pp0_iter1_reg <= icmp_ln878_reg_3502;
        icmp_ln886_26_reg_3517 <= icmp_ln886_26_fu_1668_p2;
        icmp_ln886_27_reg_3537 <= icmp_ln886_27_fu_1850_p2;
        icmp_ln886_28_reg_3547 <= icmp_ln886_28_fu_1944_p2;
        icmp_ln886_29_reg_3567 <= icmp_ln886_29_fu_2126_p2;
        icmp_ln886_30_reg_3577 <= icmp_ln886_30_fu_2220_p2;
        icmp_ln886_31_reg_3597 <= icmp_ln886_31_fu_2402_p2;
        icmp_ln886_32_reg_3607 <= icmp_ln886_32_fu_2496_p2;
        icmp_ln886_33_reg_3627 <= icmp_ln886_33_fu_2678_p2;
        icmp_ln886_33_reg_3627_pp0_iter1_reg <= icmp_ln886_33_reg_3627;
        icmp_ln886_34_reg_3637 <= icmp_ln886_34_fu_2772_p2;
        icmp_ln886_34_reg_3637_pp0_iter1_reg <= icmp_ln886_34_reg_3637;
        p_read1010_reg_3487 <= p_read10_int_reg;
        p_read88_reg_3497 <= p_read8_int_reg;
        p_read99_reg_3492 <= p_read9_int_reg;
        p_read_10_reg_3437 <= p_read44_int_reg;
        p_read_11_reg_3442 <= p_read43_int_reg;
        p_read_12_reg_3447 <= p_read42_int_reg;
        p_read_24_reg_3452 <= p_read30_int_reg;
        p_read_24_reg_3452_pp0_iter1_reg <= p_read_24_reg_3452;
        p_read_25_reg_3457 <= p_read29_int_reg;
        p_read_25_reg_3457_pp0_iter1_reg <= p_read_25_reg_3457;
        p_read_26_reg_3462 <= p_read28_int_reg;
        p_read_27_reg_3467 <= p_read27_int_reg;
        p_read_28_reg_3472 <= p_read26_int_reg;
        p_read_41_reg_3477 <= p_read12_int_reg;
        p_read_41_reg_3477_pp0_iter1_reg <= p_read_41_reg_3477;
        p_read_42_reg_3482 <= p_read11_int_reg;
        p_read_8_reg_3427 <= p_read46_int_reg;
        p_read_8_reg_3427_pp0_iter1_reg <= p_read_8_reg_3427;
        p_read_9_reg_3432 <= p_read45_int_reg;
        p_read_9_reg_3432_pp0_iter1_reg <= p_read_9_reg_3432;
        select_ln890_15_reg_3510 <= select_ln890_15_fu_1660_p3;
        x_read_reg_3422 <= x_int_reg;
        x_read_reg_3422_pp0_iter1_reg <= x_read_reg_3422;
        y_read_reg_3417 <= y_int_reg;
        y_read_reg_3417_pp0_iter1_reg <= y_read_reg_3417;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        hit_dt_int_reg <= hit_dt;
        p_read10_int_reg <= p_read10;
        p_read11_int_reg <= p_read11;
        p_read12_int_reg <= p_read12;
        p_read13_int_reg <= p_read13;
        p_read14_int_reg <= p_read14;
        p_read15_int_reg <= p_read15;
        p_read16_int_reg <= p_read16;
        p_read17_int_reg <= p_read17;
        p_read18_int_reg <= p_read18;
        p_read19_int_reg <= p_read19;
        p_read20_int_reg <= p_read20;
        p_read21_int_reg <= p_read21;
        p_read22_int_reg <= p_read22;
        p_read23_int_reg <= p_read23;
        p_read24_int_reg <= p_read24;
        p_read25_int_reg <= p_read25;
        p_read26_int_reg <= p_read26;
        p_read27_int_reg <= p_read27;
        p_read28_int_reg <= p_read28;
        p_read29_int_reg <= p_read29;
        p_read30_int_reg <= p_read30;
        p_read31_int_reg <= p_read31;
        p_read32_int_reg <= p_read32;
        p_read33_int_reg <= p_read33;
        p_read34_int_reg <= p_read34;
        p_read35_int_reg <= p_read35;
        p_read36_int_reg <= p_read36;
        p_read37_int_reg <= p_read37;
        p_read38_int_reg <= p_read38;
        p_read39_int_reg <= p_read39;
        p_read40_int_reg <= p_read40;
        p_read41_int_reg <= p_read41;
        p_read42_int_reg <= p_read42;
        p_read43_int_reg <= p_read43;
        p_read44_int_reg <= p_read44;
        p_read45_int_reg <= p_read45;
        p_read46_int_reg <= p_read46;
        p_read47_int_reg <= p_read47;
        p_read48_int_reg <= p_read48;
        p_read49_int_reg <= p_read49;
        p_read50_int_reg <= p_read50;
        p_read51_int_reg <= p_read51;
        p_read52_int_reg <= p_read52;
        p_read53_int_reg <= p_read53;
        p_read54_int_reg <= p_read54;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read9_int_reg <= p_read9;
        seed_threshold_int_reg <= seed_threshold;
        x_int_reg <= x;
        y_int_reg <= y;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (icmp_ln878_reg_3502_pp0_iter0_reg == 1'd0))) begin
        select_ln890_32_reg_3667 <= select_ln890_32_fu_3242_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = x_cast_fu_3249_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = y_read_reg_3417_pp0_iter1_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = select_ln886_24_fu_3352_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = select_ln886_25_fu_3366_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = select_ln886_26_fu_3380_p3;
    end
end

assign add_ln208_10_fu_3025_p2 = (select_ln890_15_reg_3510 + zext_ln208_14_fu_3022_p1);

assign add_ln208_11_fu_3045_p2 = (select_ln890_17_fu_3036_p3 + zext_ln208_15_fu_3042_p1);

assign add_ln208_12_fu_3068_p2 = (select_ln890_19_fu_3058_p3 + zext_ln208_4_fu_3065_p1);

assign add_ln208_13_fu_3091_p2 = (select_ln890_20_fu_3081_p3 + zext_ln208_16_fu_3088_p1);

assign add_ln208_14_fu_3114_p2 = (select_ln890_22_fu_3104_p3 + zext_ln208_17_fu_3111_p1);

assign add_ln208_15_fu_3137_p2 = (select_ln890_24_fu_3127_p3 + zext_ln208_5_fu_3134_p1);

assign add_ln208_16_fu_3160_p2 = (select_ln890_25_fu_3150_p3 + zext_ln208_18_fu_3157_p1);

assign add_ln208_17_fu_3183_p2 = (select_ln890_27_fu_3173_p3 + zext_ln208_19_fu_3180_p1);

assign add_ln208_18_fu_3206_p2 = (select_ln890_29_fu_3196_p3 + zext_ln208_6_fu_3203_p1);

assign add_ln208_19_fu_3229_p2 = (select_ln890_30_fu_3219_p3 + zext_ln208_20_fu_3226_p1);

assign add_ln208_1_fu_648_p2 = (zext_ln886_2_fu_598_p1 + zext_ln208_2_fu_644_p1);

assign add_ln208_20_fu_3255_p2 = (select_ln890_32_reg_3667 + zext_ln208_21_fu_3252_p1);

assign add_ln208_21_fu_3275_p2 = (select_ln890_34_fu_3266_p3 + zext_ln208_7_fu_3272_p1);

assign add_ln208_22_fu_3298_p2 = (select_ln890_35_fu_3288_p3 + zext_ln208_22_fu_3295_p1);

assign add_ln208_23_fu_3321_p2 = (select_ln890_37_fu_3311_p3 + zext_ln208_23_fu_3318_p1);

assign add_ln208_24_fu_2958_p2 = (zext_ln256_fu_798_p1 + zext_ln256_8_fu_2954_p1);

assign add_ln208_25_fu_2968_p2 = (zext_ln256_1_fu_1156_p1 + zext_ln256_2_fu_1510_p1);

assign add_ln208_26_fu_2978_p2 = (zext_ln208_26_fu_2974_p1 + zext_ln208_25_fu_2964_p1);

assign add_ln208_27_fu_2984_p2 = (zext_ln256_3_fu_1828_p1 + zext_ln256_4_fu_2104_p1);

assign add_ln208_28_fu_2994_p2 = (zext_ln256_6_fu_2656_p1 + zext_ln256_7_fu_2932_p1);

assign add_ln208_29_fu_3004_p2 = (zext_ln208_28_fu_3000_p1 + zext_ln256_5_fu_2380_p1);

assign add_ln208_2_fu_764_p2 = (select_ln890_2_fu_708_p3 + zext_ln208_24_fu_760_p1);

assign add_ln208_30_fu_3010_p2 = (add_ln208_29_fu_3004_p2 + zext_ln208_27_fu_2990_p1);

assign add_ln208_3_fu_898_p2 = (zext_ln886_3_fu_836_p1 + zext_ln208_8_fu_894_p1);

assign add_ln208_4_fu_1006_p2 = (select_ln890_5_fu_952_p3 + zext_ln208_9_fu_1002_p1);

assign add_ln208_5_fu_1122_p2 = (select_ln890_7_fu_1066_p3 + zext_ln208_10_fu_1118_p1);

assign add_ln208_6_fu_1252_p2 = (select_ln890_9_fu_1186_p3 + zext_ln208_11_fu_1248_p1);

assign add_ln208_7_fu_1360_p2 = (select_ln890_10_fu_1306_p3 + zext_ln208_12_fu_1356_p1);

assign add_ln208_8_fu_1476_p2 = (select_ln890_12_fu_1420_p3 + zext_ln208_13_fu_1472_p1);

assign add_ln208_9_fu_1606_p2 = (select_ln890_14_fu_1540_p3 + zext_ln208_3_fu_1602_p1);

assign add_ln208_fu_542_p2 = (zext_ln208_1_fu_538_p1 + zext_ln238_fu_468_p1);

assign add_ln213_1_fu_1112_p2 = (select_ln890_6_fu_1032_p3 + 2'd1);

assign add_ln213_2_fu_1466_p2 = (select_ln890_11_fu_1386_p3 + 2'd1);

assign add_ln213_3_fu_1794_p2 = (select_ln890_16_fu_1730_p3 + 2'd1);

assign add_ln213_4_fu_2070_p2 = (select_ln890_21_fu_2006_p3 + 2'd1);

assign add_ln213_5_fu_2346_p2 = (select_ln890_26_fu_2282_p3 + 2'd1);

assign add_ln213_6_fu_2622_p2 = (select_ln890_31_fu_2558_p3 + 2'd1);

assign add_ln213_7_fu_2898_p2 = (select_ln890_36_fu_2834_p3 + 2'd1);

assign add_ln213_fu_754_p2 = (select_ln890_1_fu_674_p3 + 2'd1);

assign and_ln890_10_fu_1172_p2 = (or_ln890_5_fu_1166_p2 & and_ln890_8_fu_1052_p2);

assign and_ln890_11_fu_1264_p2 = (xor_ln886_4_fu_1258_p2 & icmp_ln890_11_fu_1230_p2);

assign and_ln890_12_fu_1292_p2 = (or_ln890_6_fu_1286_p2 & and_ln890_10_fu_1172_p2);

assign and_ln890_13_fu_1380_p2 = (xor_ln886_5_fu_1374_p2 & icmp_ln890_12_fu_1330_p2);

assign and_ln890_14_fu_1406_p2 = (or_ln890_7_fu_1400_p2 & and_ln890_12_fu_1292_p2);

assign and_ln890_15_fu_1496_p2 = (xor_ln256_2_fu_1490_p2 & icmp_ln890_13_fu_1448_p2);

assign and_ln890_16_fu_1526_p2 = (or_ln890_8_fu_1520_p2 & and_ln890_14_fu_1406_p2);

assign and_ln890_17_fu_1618_p2 = (xor_ln886_6_fu_1612_p2 & icmp_ln890_3_fu_1584_p2);

assign and_ln890_18_fu_1646_p2 = (or_ln890_9_fu_1640_p2 & and_ln890_16_fu_1526_p2);

assign and_ln890_19_fu_1724_p2 = (xor_ln886_7_fu_1718_p2 & icmp_ln890_14_fu_1684_p2);

assign and_ln890_1_fu_668_p2 = (xor_ln886_1_fu_662_p2 & icmp_ln890_1_fu_618_p2);

assign and_ln890_20_fu_1750_p2 = (or_ln890_10_fu_1744_p2 & and_ln890_18_fu_1646_p2);

assign and_ln890_21_fu_1814_p2 = (xor_ln256_3_fu_1808_p2 & icmp_ln890_15_fu_1776_p2);

assign and_ln890_22_fu_1844_p2 = (or_ln890_11_fu_1838_p2 & and_ln890_20_fu_1750_p2);

assign and_ln890_23_fu_1910_p2 = (xor_ln886_8_fu_1904_p2 & icmp_ln890_4_fu_1886_p2);

assign and_ln890_24_fu_1938_p2 = (or_ln890_12_fu_1932_p2 & and_ln890_22_fu_1844_p2);

assign and_ln890_25_fu_2000_p2 = (xor_ln886_9_fu_1994_p2 & icmp_ln890_16_fu_1960_p2);

assign and_ln890_26_fu_2026_p2 = (or_ln890_13_fu_2020_p2 & and_ln890_24_fu_1938_p2);

assign and_ln890_27_fu_2090_p2 = (xor_ln256_4_fu_2084_p2 & icmp_ln890_17_fu_2052_p2);

assign and_ln890_28_fu_2120_p2 = (or_ln890_14_fu_2114_p2 & and_ln890_26_fu_2026_p2);

assign and_ln890_29_fu_2186_p2 = (xor_ln886_10_fu_2180_p2 & icmp_ln890_5_fu_2162_p2);

assign and_ln890_2_fu_694_p2 = (or_ln890_fu_576_p2 & or_ln890_1_fu_688_p2);

assign and_ln890_30_fu_2214_p2 = (or_ln890_15_fu_2208_p2 & and_ln890_28_fu_2120_p2);

assign and_ln890_31_fu_2276_p2 = (xor_ln886_11_fu_2270_p2 & icmp_ln890_18_fu_2236_p2);

assign and_ln890_32_fu_2302_p2 = (or_ln890_16_fu_2296_p2 & and_ln890_30_fu_2214_p2);

assign and_ln890_33_fu_2366_p2 = (xor_ln256_5_fu_2360_p2 & icmp_ln890_19_fu_2328_p2);

assign and_ln890_34_fu_2396_p2 = (or_ln890_17_fu_2390_p2 & and_ln890_32_fu_2302_p2);

assign and_ln890_35_fu_2462_p2 = (xor_ln886_12_fu_2456_p2 & icmp_ln890_6_fu_2438_p2);

assign and_ln890_36_fu_2490_p2 = (or_ln890_18_fu_2484_p2 & and_ln890_34_fu_2396_p2);

assign and_ln890_37_fu_2552_p2 = (xor_ln886_13_fu_2546_p2 & icmp_ln890_20_fu_2512_p2);

assign and_ln890_38_fu_2578_p2 = (or_ln890_19_fu_2572_p2 & and_ln890_36_fu_2490_p2);

assign and_ln890_39_fu_2642_p2 = (xor_ln256_6_fu_2636_p2 & icmp_ln890_21_fu_2604_p2);

assign and_ln890_3_fu_784_p2 = (xor_ln256_fu_778_p2 & icmp_ln890_2_fu_736_p2);

assign and_ln890_40_fu_2672_p2 = (or_ln890_20_fu_2666_p2 & and_ln890_38_fu_2578_p2);

assign and_ln890_41_fu_2738_p2 = (xor_ln886_14_fu_2732_p2 & icmp_ln890_7_fu_2714_p2);

assign and_ln890_42_fu_2766_p2 = (or_ln890_21_fu_2760_p2 & and_ln890_40_fu_2672_p2);

assign and_ln890_43_fu_2828_p2 = (xor_ln886_15_fu_2822_p2 & icmp_ln890_22_fu_2788_p2);

assign and_ln890_44_fu_2854_p2 = (or_ln890_22_fu_2848_p2 & and_ln890_42_fu_2766_p2);

assign and_ln890_45_fu_2918_p2 = (xor_ln256_7_fu_2912_p2 & icmp_ln890_23_fu_2880_p2);

assign and_ln890_46_fu_2948_p2 = (or_ln890_23_fu_2942_p2 & and_ln890_44_fu_2854_p2);

assign and_ln890_4_fu_814_p2 = (or_ln890_2_fu_808_p2 & and_ln890_2_fu_694_p2);

assign and_ln890_5_fu_910_p2 = (xor_ln886_2_fu_904_p2 & icmp_ln890_8_fu_876_p2);

assign and_ln890_6_fu_938_p2 = (or_ln890_3_fu_932_p2 & and_ln890_4_fu_814_p2);

assign and_ln890_7_fu_1026_p2 = (xor_ln886_3_fu_1020_p2 & icmp_ln890_9_fu_976_p2);

assign and_ln890_8_fu_1052_p2 = (or_ln890_4_fu_1046_p2 & and_ln890_6_fu_938_p2);

assign and_ln890_9_fu_1142_p2 = (xor_ln256_1_fu_1136_p2 & icmp_ln890_10_fu_1094_p2);

assign and_ln890_fu_554_p2 = (xor_ln886_fu_548_p2 & icmp_ln890_fu_520_p2);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign cc_nhits_V_fu_3016_p2 = (add_ln208_30_fu_3010_p2 + add_ln208_26_fu_2978_p2);

assign icmp_ln243_1_fu_882_p2 = ((p_read21_int_reg < p_read23_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_2_fu_1236_p2 = ((p_read21_int_reg < p_read24_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_3_fu_1590_p2 = ((p_read21_int_reg < p_read25_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_4_fu_1892_p2 = ((p_read21_int_reg < p_read26_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_5_fu_2168_p2 = ((p_read21_int_reg < p_read27_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_6_fu_2444_p2 = ((p_read21_int_reg < p_read28_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_7_fu_2720_p2 = ((p_read21_int_reg < p_read29_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_526_p2 = ((p_read21_int_reg < p_read22_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_1_fu_982_p2 = ((p_read21_int_reg < p_read6_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_2_fu_1336_p2 = ((p_read21_int_reg < p_read7_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_3_fu_1690_p2 = ((p_read21_int_reg < p_read8_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_4_fu_1966_p2 = ((p_read21_int_reg < p_read9_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_5_fu_2242_p2 = ((p_read21_int_reg < p_read10_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_6_fu_2518_p2 = ((p_read21_int_reg < p_read11_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_7_fu_2794_p2 = ((p_read21_int_reg < p_read12_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln250_fu_624_p2 = ((p_read21_int_reg < p_read5_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln256_1_fu_1074_p2 = ((p_read40_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_2_fu_1428_p2 = ((p_read41_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_3_fu_1756_p2 = ((p_read42_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_4_fu_2032_p2 = ((p_read43_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_5_fu_2308_p2 = ((p_read44_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_6_fu_2584_p2 = ((p_read45_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_7_fu_2860_p2 = ((p_read46_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_716_p2 = ((p_read39_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln257_1_fu_1100_p2 = ((p_read21_int_reg < p_read40_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_2_fu_1454_p2 = ((p_read21_int_reg < p_read41_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_3_fu_1782_p2 = ((p_read21_int_reg < p_read42_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_4_fu_2058_p2 = ((p_read21_int_reg < p_read43_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_5_fu_2334_p2 = ((p_read21_int_reg < p_read44_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_6_fu_2610_p2 = ((p_read21_int_reg < p_read45_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_7_fu_2886_p2 = ((p_read21_int_reg < p_read46_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_742_p2 = ((p_read21_int_reg < p_read39_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_490_p2 = ((p_read30_int_reg < p_read31_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_846_p2 = ((p_read30_int_reg < p_read32_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_1200_p2 = ((p_read30_int_reg < p_read33_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_1554_p2 = ((p_read30_int_reg < p_read34_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_5_fu_1856_p2 = ((p_read30_int_reg < p_read35_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_6_fu_2132_p2 = ((p_read30_int_reg < p_read36_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_7_fu_2408_p2 = ((p_read30_int_reg < p_read37_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_8_fu_2684_p2 = ((p_read30_int_reg < p_read38_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_458_p2 = ((p_read21_int_reg < seed_threshold_int_reg) ? 1'b1 : 1'b0);

assign icmp_ln878_reg_3502_pp0_iter0_reg = icmp_ln878_reg_3502;

assign icmp_ln886_20_fu_602_p2 = ((p_read5_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_21_fu_840_p2 = ((p_read23_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_22_fu_960_p2 = ((p_read6_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_23_fu_1194_p2 = ((p_read24_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_24_fu_1314_p2 = ((p_read7_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_25_fu_1548_p2 = ((p_read25_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_26_fu_1668_p2 = ((p_read8_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_27_fu_1850_p2 = ((p_read26_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_28_fu_1944_p2 = ((p_read9_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_29_fu_2126_p2 = ((p_read27_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_30_fu_2220_p2 = ((p_read10_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_31_fu_2402_p2 = ((p_read28_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_32_fu_2496_p2 = ((p_read11_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_33_fu_2678_p2 = ((p_read29_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_34_fu_2772_p2 = ((p_read12_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_484_p2 = ((p_read22_int_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln890_10_fu_1094_p2 = ((sub_ln213_13_fu_1088_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_11_fu_1230_p2 = ((select_ln213_2_fu_1222_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_12_fu_1330_p2 = ((sub_ln213_15_fu_1324_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_13_fu_1448_p2 = ((sub_ln213_16_fu_1442_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_14_fu_1684_p2 = ((sub_ln213_18_fu_1678_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_15_fu_1776_p2 = ((sub_ln213_19_fu_1770_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_16_fu_1960_p2 = ((sub_ln213_21_fu_1954_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_17_fu_2052_p2 = ((sub_ln213_22_fu_2046_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_18_fu_2236_p2 = ((sub_ln213_24_fu_2230_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_19_fu_2328_p2 = ((sub_ln213_25_fu_2322_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_1_fu_618_p2 = ((sub_ln213_8_fu_612_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_20_fu_2512_p2 = ((sub_ln213_27_fu_2506_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_21_fu_2604_p2 = ((sub_ln213_28_fu_2598_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_22_fu_2788_p2 = ((sub_ln213_30_fu_2782_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_23_fu_2880_p2 = ((sub_ln213_31_fu_2874_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_2_fu_736_p2 = ((sub_ln213_9_fu_730_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_3_fu_1584_p2 = ((select_ln213_3_fu_1576_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_4_fu_1886_p2 = ((select_ln213_4_fu_1878_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_5_fu_2162_p2 = ((select_ln213_5_fu_2154_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_6_fu_2438_p2 = ((select_ln213_6_fu_2430_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_7_fu_2714_p2 = ((select_ln213_7_fu_2706_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_8_fu_876_p2 = ((select_ln213_1_fu_868_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_9_fu_976_p2 = ((sub_ln213_12_fu_970_p2 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign icmp_ln890_fu_520_p2 = ((select_ln213_fu_512_p3 > zext_ln886_fu_480_p1) ? 1'b1 : 1'b0);

assign or_ln213_1_fu_1080_p3 = {{1'd1}, {p_read48_int_reg}};

assign or_ln213_2_fu_1434_p3 = {{1'd1}, {p_read49_int_reg}};

assign or_ln213_3_fu_1762_p3 = {{1'd1}, {p_read50_int_reg}};

assign or_ln213_4_fu_2038_p3 = {{1'd1}, {p_read51_int_reg}};

assign or_ln213_5_fu_2314_p3 = {{1'd1}, {p_read52_int_reg}};

assign or_ln213_6_fu_2590_p3 = {{1'd1}, {p_read53_int_reg}};

assign or_ln213_7_fu_2866_p3 = {{1'd1}, {p_read54_int_reg}};

assign or_ln256_1_fu_1160_p2 = (xor_ln257_1_fu_1106_p2 | icmp_ln256_1_fu_1074_p2);

assign or_ln256_2_fu_1514_p2 = (xor_ln257_2_fu_1460_p2 | icmp_ln256_2_fu_1428_p2);

assign or_ln256_3_fu_1832_p2 = (xor_ln257_3_fu_1788_p2 | icmp_ln256_3_fu_1756_p2);

assign or_ln256_4_fu_2108_p2 = (xor_ln257_4_fu_2064_p2 | icmp_ln256_4_fu_2032_p2);

assign or_ln256_5_fu_2384_p2 = (xor_ln257_5_fu_2340_p2 | icmp_ln256_5_fu_2308_p2);

assign or_ln256_6_fu_2660_p2 = (xor_ln257_6_fu_2616_p2 | icmp_ln256_6_fu_2584_p2);

assign or_ln256_7_fu_2936_p2 = (xor_ln257_7_fu_2892_p2 | icmp_ln256_7_fu_2860_p2);

assign or_ln256_fu_802_p2 = (xor_ln257_fu_748_p2 | icmp_ln256_fu_716_p2);

assign or_ln886_10_fu_2202_p2 = (xor_ln243_5_fu_2174_p2 | icmp_ln886_29_fu_2126_p2);

assign or_ln886_11_fu_2290_p2 = (xor_ln250_5_fu_2248_p2 | icmp_ln886_30_fu_2220_p2);

assign or_ln886_12_fu_2478_p2 = (xor_ln243_6_fu_2450_p2 | icmp_ln886_31_fu_2402_p2);

assign or_ln886_13_fu_2566_p2 = (xor_ln250_6_fu_2524_p2 | icmp_ln886_32_fu_2496_p2);

assign or_ln886_14_fu_2754_p2 = (xor_ln243_7_fu_2726_p2 | icmp_ln886_33_fu_2678_p2);

assign or_ln886_15_fu_2842_p2 = (xor_ln250_7_fu_2800_p2 | icmp_ln886_34_fu_2772_p2);

assign or_ln886_16_fu_3348_p2 = (icmp_ln878_reg_3502_pp0_iter1_reg | and_ln890_46_reg_3657_pp0_iter1_reg);

assign or_ln886_1_fu_682_p2 = (xor_ln250_fu_630_p2 | icmp_ln886_20_fu_602_p2);

assign or_ln886_2_fu_926_p2 = (xor_ln243_1_fu_888_p2 | icmp_ln886_21_fu_840_p2);

assign or_ln886_3_fu_1040_p2 = (xor_ln250_1_fu_988_p2 | icmp_ln886_22_fu_960_p2);

assign or_ln886_4_fu_1280_p2 = (xor_ln243_2_fu_1242_p2 | icmp_ln886_23_fu_1194_p2);

assign or_ln886_5_fu_1394_p2 = (xor_ln250_2_fu_1342_p2 | icmp_ln886_24_fu_1314_p2);

assign or_ln886_6_fu_1634_p2 = (xor_ln243_3_fu_1596_p2 | icmp_ln886_25_fu_1548_p2);

assign or_ln886_7_fu_1738_p2 = (xor_ln250_3_fu_1696_p2 | icmp_ln886_26_fu_1668_p2);

assign or_ln886_8_fu_1926_p2 = (xor_ln243_4_fu_1898_p2 | icmp_ln886_27_fu_1850_p2);

assign or_ln886_9_fu_2014_p2 = (xor_ln250_4_fu_1972_p2 | icmp_ln886_28_fu_1944_p2);

assign or_ln886_fu_570_p2 = (xor_ln243_fu_532_p2 | icmp_ln886_fu_484_p2);

assign or_ln890_10_fu_1744_p2 = (or_ln886_7_fu_1738_p2 | and_ln890_19_fu_1724_p2);

assign or_ln890_11_fu_1838_p2 = (or_ln256_3_fu_1832_p2 | and_ln890_21_fu_1814_p2);

assign or_ln890_12_fu_1932_p2 = (or_ln886_8_fu_1926_p2 | and_ln890_23_fu_1910_p2);

assign or_ln890_13_fu_2020_p2 = (or_ln886_9_fu_2014_p2 | and_ln890_25_fu_2000_p2);

assign or_ln890_14_fu_2114_p2 = (or_ln256_4_fu_2108_p2 | and_ln890_27_fu_2090_p2);

assign or_ln890_15_fu_2208_p2 = (or_ln886_10_fu_2202_p2 | and_ln890_29_fu_2186_p2);

assign or_ln890_16_fu_2296_p2 = (or_ln886_11_fu_2290_p2 | and_ln890_31_fu_2276_p2);

assign or_ln890_17_fu_2390_p2 = (or_ln256_5_fu_2384_p2 | and_ln890_33_fu_2366_p2);

assign or_ln890_18_fu_2484_p2 = (or_ln886_12_fu_2478_p2 | and_ln890_35_fu_2462_p2);

assign or_ln890_19_fu_2572_p2 = (or_ln886_13_fu_2566_p2 | and_ln890_37_fu_2552_p2);

assign or_ln890_1_fu_688_p2 = (or_ln886_1_fu_682_p2 | and_ln890_1_fu_668_p2);

assign or_ln890_20_fu_2666_p2 = (or_ln256_6_fu_2660_p2 | and_ln890_39_fu_2642_p2);

assign or_ln890_21_fu_2760_p2 = (or_ln886_14_fu_2754_p2 | and_ln890_41_fu_2738_p2);

assign or_ln890_22_fu_2848_p2 = (or_ln886_15_fu_2842_p2 | and_ln890_43_fu_2828_p2);

assign or_ln890_23_fu_2942_p2 = (or_ln256_7_fu_2936_p2 | and_ln890_45_fu_2918_p2);

assign or_ln890_2_fu_808_p2 = (or_ln256_fu_802_p2 | and_ln890_3_fu_784_p2);

assign or_ln890_3_fu_932_p2 = (or_ln886_2_fu_926_p2 | and_ln890_5_fu_910_p2);

assign or_ln890_4_fu_1046_p2 = (or_ln886_3_fu_1040_p2 | and_ln890_7_fu_1026_p2);

assign or_ln890_5_fu_1166_p2 = (or_ln256_1_fu_1160_p2 | and_ln890_9_fu_1142_p2);

assign or_ln890_6_fu_1286_p2 = (or_ln886_4_fu_1280_p2 | and_ln890_11_fu_1264_p2);

assign or_ln890_7_fu_1400_p2 = (or_ln886_5_fu_1394_p2 | and_ln890_13_fu_1380_p2);

assign or_ln890_8_fu_1520_p2 = (or_ln256_2_fu_1514_p2 | and_ln890_15_fu_1496_p2);

assign or_ln890_9_fu_1640_p2 = (or_ln886_6_fu_1634_p2 | and_ln890_17_fu_1618_p2);

assign or_ln890_fu_576_p2 = (or_ln886_fu_570_p2 | and_ln890_fu_554_p2);

assign or_ln_fu_722_p3 = {{1'd1}, {p_read47_int_reg}};

assign select_ln213_10_fu_1348_p3 = ((xor_ln890_2_fu_1270_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_11_fu_1702_p3 = ((xor_ln890_3_fu_1624_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_12_fu_1978_p3 = ((xor_ln890_4_fu_1916_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_13_fu_2254_p3 = ((xor_ln890_5_fu_2192_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_14_fu_2530_p3 = ((xor_ln890_6_fu_2468_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_15_fu_2806_p3 = ((xor_ln890_7_fu_2744_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_1_fu_868_p3 = ((icmp_ln878_2_fu_846_p2[0:0] == 1'b1) ? sub_ln213_10_fu_856_p2 : sub_ln213_11_fu_862_p2);

assign select_ln213_2_fu_1222_p3 = ((icmp_ln878_3_fu_1200_p2[0:0] == 1'b1) ? sub_ln213_2_fu_1210_p2 : sub_ln213_14_fu_1216_p2);

assign select_ln213_3_fu_1576_p3 = ((icmp_ln878_4_fu_1554_p2[0:0] == 1'b1) ? sub_ln213_3_fu_1564_p2 : sub_ln213_17_fu_1570_p2);

assign select_ln213_4_fu_1878_p3 = ((icmp_ln878_5_fu_1856_p2[0:0] == 1'b1) ? sub_ln213_4_fu_1866_p2 : sub_ln213_20_fu_1872_p2);

assign select_ln213_5_fu_2154_p3 = ((icmp_ln878_6_fu_2132_p2[0:0] == 1'b1) ? sub_ln213_5_fu_2142_p2 : sub_ln213_23_fu_2148_p2);

assign select_ln213_6_fu_2430_p3 = ((icmp_ln878_7_fu_2408_p2[0:0] == 1'b1) ? sub_ln213_6_fu_2418_p2 : sub_ln213_26_fu_2424_p2);

assign select_ln213_7_fu_2706_p3 = ((icmp_ln878_8_fu_2684_p2[0:0] == 1'b1) ? sub_ln213_7_fu_2694_p2 : sub_ln213_29_fu_2700_p2);

assign select_ln213_8_fu_636_p3 = ((xor_ln890_fu_560_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_9_fu_994_p3 = ((xor_ln890_1_fu_916_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln213_fu_512_p3 = ((icmp_ln878_1_fu_490_p2[0:0] == 1'b1) ? sub_ln213_fu_500_p2 : sub_ln213_1_fu_506_p2);

assign select_ln256_10_fu_2352_p3 = ((icmp_ln256_5_fu_2308_p2[0:0] == 1'b1) ? select_ln890_26_fu_2282_p3 : add_ln213_5_fu_2346_p2);

assign select_ln256_11_fu_3189_p3 = ((icmp_ln256_5_reg_3587[0:0] == 1'b1) ? select_ln890_27_fu_3173_p3 : add_ln208_17_fu_3183_p2);

assign select_ln256_12_fu_2628_p3 = ((icmp_ln256_6_fu_2584_p2[0:0] == 1'b1) ? select_ln890_31_fu_2558_p3 : add_ln213_6_fu_2622_p2);

assign select_ln256_13_fu_3260_p3 = ((icmp_ln256_6_reg_3617_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_32_reg_3667 : add_ln208_20_fu_3255_p2);

assign select_ln256_14_fu_2904_p3 = ((icmp_ln256_7_fu_2860_p2[0:0] == 1'b1) ? select_ln890_36_fu_2834_p3 : add_ln213_7_fu_2898_p2);

assign select_ln256_15_fu_3327_p3 = ((icmp_ln256_7_reg_3647_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_37_fu_3311_p3 : add_ln208_23_fu_3321_p2);

assign select_ln256_1_fu_820_p3 = ((icmp_ln256_fu_716_p2[0:0] == 1'b1) ? select_ln890_2_fu_708_p3 : add_ln208_2_fu_764_p2);

assign select_ln256_2_fu_1128_p3 = ((icmp_ln256_1_fu_1074_p2[0:0] == 1'b1) ? select_ln890_6_fu_1032_p3 : add_ln213_1_fu_1112_p2);

assign select_ln256_3_fu_1178_p3 = ((icmp_ln256_1_fu_1074_p2[0:0] == 1'b1) ? select_ln890_7_fu_1066_p3 : add_ln208_5_fu_1122_p2);

assign select_ln256_4_fu_1482_p3 = ((icmp_ln256_2_fu_1428_p2[0:0] == 1'b1) ? select_ln890_11_fu_1386_p3 : add_ln213_2_fu_1466_p2);

assign select_ln256_5_fu_1532_p3 = ((icmp_ln256_2_fu_1428_p2[0:0] == 1'b1) ? select_ln890_12_fu_1420_p3 : add_ln208_8_fu_1476_p2);

assign select_ln256_6_fu_1800_p3 = ((icmp_ln256_3_fu_1756_p2[0:0] == 1'b1) ? select_ln890_16_fu_1730_p3 : add_ln213_3_fu_1794_p2);

assign select_ln256_7_fu_3051_p3 = ((icmp_ln256_3_reg_3527[0:0] == 1'b1) ? select_ln890_17_fu_3036_p3 : add_ln208_11_fu_3045_p2);

assign select_ln256_8_fu_2076_p3 = ((icmp_ln256_4_fu_2032_p2[0:0] == 1'b1) ? select_ln890_21_fu_2006_p3 : add_ln213_4_fu_2070_p2);

assign select_ln256_9_fu_3120_p3 = ((icmp_ln256_4_reg_3557[0:0] == 1'b1) ? select_ln890_22_fu_3104_p3 : add_ln208_14_fu_3114_p2);

assign select_ln256_fu_770_p3 = ((icmp_ln256_fu_716_p2[0:0] == 1'b1) ? select_ln890_1_fu_674_p3 : add_ln213_fu_754_p2);

assign select_ln878_1_fu_3360_p3 = ((icmp_ln878_reg_3502_pp0_iter1_reg[0:0] == 1'b1) ? 3'd0 : p_read_24_reg_3452_pp0_iter1_reg);

assign select_ln878_2_fu_3374_p3 = ((icmp_ln878_reg_3502_pp0_iter1_reg[0:0] == 1'b1) ? 4'd0 : cc_nhits_V_reg_3662_pp0_iter1_reg);

assign select_ln878_fu_3341_p3 = ((icmp_ln878_reg_3502_pp0_iter1_reg[0:0] == 1'b1) ? 16'd0 : select_ln890_39_fu_3334_p3);

assign select_ln886_10_fu_1710_p3 = ((icmp_ln886_26_fu_1668_p2[0:0] == 1'b1) ? zext_ln886_6_fu_1630_p1 : select_ln213_11_fu_1702_p3);

assign select_ln886_11_fu_3030_p3 = ((icmp_ln886_26_reg_3517[0:0] == 1'b1) ? select_ln890_15_reg_3510 : add_ln208_10_fu_3025_p2);

assign select_ln886_12_fu_3074_p3 = ((icmp_ln886_27_reg_3537[0:0] == 1'b1) ? select_ln890_19_fu_3058_p3 : add_ln208_12_fu_3068_p2);

assign select_ln886_13_fu_1986_p3 = ((icmp_ln886_28_fu_1944_p2[0:0] == 1'b1) ? zext_ln886_7_fu_1922_p1 : select_ln213_12_fu_1978_p3);

assign select_ln886_14_fu_3097_p3 = ((icmp_ln886_28_reg_3547[0:0] == 1'b1) ? select_ln890_20_fu_3081_p3 : add_ln208_13_fu_3091_p2);

assign select_ln886_15_fu_3143_p3 = ((icmp_ln886_29_reg_3567[0:0] == 1'b1) ? select_ln890_24_fu_3127_p3 : add_ln208_15_fu_3137_p2);

assign select_ln886_16_fu_2262_p3 = ((icmp_ln886_30_fu_2220_p2[0:0] == 1'b1) ? zext_ln886_8_fu_2198_p1 : select_ln213_13_fu_2254_p3);

assign select_ln886_17_fu_3166_p3 = ((icmp_ln886_30_reg_3577[0:0] == 1'b1) ? select_ln890_25_fu_3150_p3 : add_ln208_16_fu_3160_p2);

assign select_ln886_18_fu_3212_p3 = ((icmp_ln886_31_reg_3597[0:0] == 1'b1) ? select_ln890_29_fu_3196_p3 : add_ln208_18_fu_3206_p2);

assign select_ln886_19_fu_2538_p3 = ((icmp_ln886_32_fu_2496_p2[0:0] == 1'b1) ? zext_ln886_9_fu_2474_p1 : select_ln213_14_fu_2530_p3);

assign select_ln886_1_fu_654_p3 = ((icmp_ln886_20_fu_602_p2[0:0] == 1'b1) ? zext_ln886_1_fu_566_p1 : select_ln213_8_fu_636_p3);

assign select_ln886_20_fu_3235_p3 = ((icmp_ln886_32_reg_3607[0:0] == 1'b1) ? select_ln890_30_fu_3219_p3 : add_ln208_19_fu_3229_p2);

assign select_ln886_21_fu_3281_p3 = ((icmp_ln886_33_reg_3627_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_34_fu_3266_p3 : add_ln208_21_fu_3275_p2);

assign select_ln886_22_fu_2814_p3 = ((icmp_ln886_34_fu_2772_p2[0:0] == 1'b1) ? zext_ln886_10_fu_2750_p1 : select_ln213_15_fu_2806_p3);

assign select_ln886_23_fu_3304_p3 = ((icmp_ln886_34_reg_3637_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_35_fu_3288_p3 : add_ln208_22_fu_3298_p2);

assign select_ln886_24_fu_3352_p3 = ((or_ln886_16_fu_3348_p2[0:0] == 1'b1) ? select_ln878_fu_3341_p3 : 16'd0);

assign select_ln886_25_fu_3366_p3 = ((or_ln886_16_fu_3348_p2[0:0] == 1'b1) ? select_ln878_1_fu_3360_p3 : 3'd0);

assign select_ln886_26_fu_3380_p3 = ((or_ln886_16_fu_3348_p2[0:0] == 1'b1) ? select_ln878_2_fu_3374_p3 : 4'd0);

assign select_ln886_2_fu_700_p3 = ((icmp_ln886_20_fu_602_p2[0:0] == 1'b1) ? zext_ln886_2_fu_598_p1 : add_ln208_1_fu_648_p2);

assign select_ln886_3_fu_944_p3 = ((icmp_ln886_21_fu_840_p2[0:0] == 1'b1) ? zext_ln886_3_fu_836_p1 : add_ln208_3_fu_898_p2);

assign select_ln886_4_fu_1012_p3 = ((icmp_ln886_22_fu_960_p2[0:0] == 1'b1) ? zext_ln886_4_fu_922_p1 : select_ln213_9_fu_994_p3);

assign select_ln886_5_fu_1058_p3 = ((icmp_ln886_22_fu_960_p2[0:0] == 1'b1) ? select_ln890_5_fu_952_p3 : add_ln208_4_fu_1006_p2);

assign select_ln886_6_fu_1298_p3 = ((icmp_ln886_23_fu_1194_p2[0:0] == 1'b1) ? select_ln890_9_fu_1186_p3 : add_ln208_6_fu_1252_p2);

assign select_ln886_7_fu_1366_p3 = ((icmp_ln886_24_fu_1314_p2[0:0] == 1'b1) ? zext_ln886_5_fu_1276_p1 : select_ln213_10_fu_1348_p3);

assign select_ln886_8_fu_1412_p3 = ((icmp_ln886_24_fu_1314_p2[0:0] == 1'b1) ? select_ln890_10_fu_1306_p3 : add_ln208_7_fu_1360_p2);

assign select_ln886_9_fu_1652_p3 = ((icmp_ln886_25_fu_1548_p2[0:0] == 1'b1) ? select_ln890_14_fu_1540_p3 : add_ln208_9_fu_1606_p2);

assign select_ln886_fu_582_p3 = ((icmp_ln886_fu_484_p2[0:0] == 1'b1) ? zext_ln238_fu_468_p1 : add_ln208_fu_542_p2);

assign select_ln890_10_fu_1306_p3 = ((and_ln890_11_fu_1264_p2[0:0] == 1'b1) ? select_ln890_9_fu_1186_p3 : select_ln886_6_fu_1298_p3);

assign select_ln890_11_fu_1386_p3 = ((and_ln890_13_fu_1380_p2[0:0] == 1'b1) ? zext_ln886_5_fu_1276_p1 : select_ln886_7_fu_1366_p3);

assign select_ln890_12_fu_1420_p3 = ((and_ln890_13_fu_1380_p2[0:0] == 1'b1) ? select_ln890_10_fu_1306_p3 : select_ln886_8_fu_1412_p3);

assign select_ln890_13_fu_1502_p3 = ((and_ln890_15_fu_1496_p2[0:0] == 1'b1) ? select_ln890_11_fu_1386_p3 : select_ln256_4_fu_1482_p3);

assign select_ln890_14_fu_1540_p3 = ((and_ln890_15_fu_1496_p2[0:0] == 1'b1) ? select_ln890_12_fu_1420_p3 : select_ln256_5_fu_1532_p3);

assign select_ln890_15_fu_1660_p3 = ((and_ln890_17_fu_1618_p2[0:0] == 1'b1) ? select_ln890_14_fu_1540_p3 : select_ln886_9_fu_1652_p3);

assign select_ln890_16_fu_1730_p3 = ((and_ln890_19_fu_1724_p2[0:0] == 1'b1) ? zext_ln886_6_fu_1630_p1 : select_ln886_10_fu_1710_p3);

assign select_ln890_17_fu_3036_p3 = ((and_ln890_19_reg_3522[0:0] == 1'b1) ? select_ln890_15_reg_3510 : select_ln886_11_fu_3030_p3);

assign select_ln890_18_fu_1820_p3 = ((and_ln890_21_fu_1814_p2[0:0] == 1'b1) ? select_ln890_16_fu_1730_p3 : select_ln256_6_fu_1800_p3);

assign select_ln890_19_fu_3058_p3 = ((and_ln890_21_reg_3532[0:0] == 1'b1) ? select_ln890_17_fu_3036_p3 : select_ln256_7_fu_3051_p3);

assign select_ln890_1_fu_674_p3 = ((and_ln890_1_fu_668_p2[0:0] == 1'b1) ? zext_ln886_1_fu_566_p1 : select_ln886_1_fu_654_p3);

assign select_ln890_20_fu_3081_p3 = ((and_ln890_23_reg_3542[0:0] == 1'b1) ? select_ln890_19_fu_3058_p3 : select_ln886_12_fu_3074_p3);

assign select_ln890_21_fu_2006_p3 = ((and_ln890_25_fu_2000_p2[0:0] == 1'b1) ? zext_ln886_7_fu_1922_p1 : select_ln886_13_fu_1986_p3);

assign select_ln890_22_fu_3104_p3 = ((and_ln890_25_reg_3552[0:0] == 1'b1) ? select_ln890_20_fu_3081_p3 : select_ln886_14_fu_3097_p3);

assign select_ln890_23_fu_2096_p3 = ((and_ln890_27_fu_2090_p2[0:0] == 1'b1) ? select_ln890_21_fu_2006_p3 : select_ln256_8_fu_2076_p3);

assign select_ln890_24_fu_3127_p3 = ((and_ln890_27_reg_3562[0:0] == 1'b1) ? select_ln890_22_fu_3104_p3 : select_ln256_9_fu_3120_p3);

assign select_ln890_25_fu_3150_p3 = ((and_ln890_29_reg_3572[0:0] == 1'b1) ? select_ln890_24_fu_3127_p3 : select_ln886_15_fu_3143_p3);

assign select_ln890_26_fu_2282_p3 = ((and_ln890_31_fu_2276_p2[0:0] == 1'b1) ? zext_ln886_8_fu_2198_p1 : select_ln886_16_fu_2262_p3);

assign select_ln890_27_fu_3173_p3 = ((and_ln890_31_reg_3582[0:0] == 1'b1) ? select_ln890_25_fu_3150_p3 : select_ln886_17_fu_3166_p3);

assign select_ln890_28_fu_2372_p3 = ((and_ln890_33_fu_2366_p2[0:0] == 1'b1) ? select_ln890_26_fu_2282_p3 : select_ln256_10_fu_2352_p3);

assign select_ln890_29_fu_3196_p3 = ((and_ln890_33_reg_3592[0:0] == 1'b1) ? select_ln890_27_fu_3173_p3 : select_ln256_11_fu_3189_p3);

assign select_ln890_2_fu_708_p3 = ((and_ln890_1_fu_668_p2[0:0] == 1'b1) ? zext_ln886_2_fu_598_p1 : select_ln886_2_fu_700_p3);

assign select_ln890_30_fu_3219_p3 = ((and_ln890_35_reg_3602[0:0] == 1'b1) ? select_ln890_29_fu_3196_p3 : select_ln886_18_fu_3212_p3);

assign select_ln890_31_fu_2558_p3 = ((and_ln890_37_fu_2552_p2[0:0] == 1'b1) ? zext_ln886_9_fu_2474_p1 : select_ln886_19_fu_2538_p3);

assign select_ln890_32_fu_3242_p3 = ((and_ln890_37_reg_3612[0:0] == 1'b1) ? select_ln890_30_fu_3219_p3 : select_ln886_20_fu_3235_p3);

assign select_ln890_33_fu_2648_p3 = ((and_ln890_39_fu_2642_p2[0:0] == 1'b1) ? select_ln890_31_fu_2558_p3 : select_ln256_12_fu_2628_p3);

assign select_ln890_34_fu_3266_p3 = ((and_ln890_39_reg_3622_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_32_reg_3667 : select_ln256_13_fu_3260_p3);

assign select_ln890_35_fu_3288_p3 = ((and_ln890_41_reg_3632_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_34_fu_3266_p3 : select_ln886_21_fu_3281_p3);

assign select_ln890_36_fu_2834_p3 = ((and_ln890_43_fu_2828_p2[0:0] == 1'b1) ? zext_ln886_10_fu_2750_p1 : select_ln886_22_fu_2814_p3);

assign select_ln890_37_fu_3311_p3 = ((and_ln890_43_reg_3642_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_35_fu_3288_p3 : select_ln886_23_fu_3304_p3);

assign select_ln890_38_fu_2924_p3 = ((and_ln890_45_fu_2918_p2[0:0] == 1'b1) ? select_ln890_36_fu_2834_p3 : select_ln256_14_fu_2904_p3);

assign select_ln890_39_fu_3334_p3 = ((and_ln890_45_reg_3652_pp0_iter1_reg[0:0] == 1'b1) ? select_ln890_37_fu_3311_p3 : select_ln256_15_fu_3327_p3);

assign select_ln890_3_fu_790_p3 = ((and_ln890_3_fu_784_p2[0:0] == 1'b1) ? select_ln890_1_fu_674_p3 : select_ln256_fu_770_p3);

assign select_ln890_4_fu_828_p3 = ((and_ln890_3_fu_784_p2[0:0] == 1'b1) ? select_ln890_2_fu_708_p3 : select_ln256_1_fu_820_p3);

assign select_ln890_5_fu_952_p3 = ((and_ln890_5_fu_910_p2[0:0] == 1'b1) ? zext_ln886_3_fu_836_p1 : select_ln886_3_fu_944_p3);

assign select_ln890_6_fu_1032_p3 = ((and_ln890_7_fu_1026_p2[0:0] == 1'b1) ? zext_ln886_4_fu_922_p1 : select_ln886_4_fu_1012_p3);

assign select_ln890_7_fu_1066_p3 = ((and_ln890_7_fu_1026_p2[0:0] == 1'b1) ? select_ln890_5_fu_952_p3 : select_ln886_5_fu_1058_p3);

assign select_ln890_8_fu_1148_p3 = ((and_ln890_9_fu_1142_p2[0:0] == 1'b1) ? select_ln890_6_fu_1032_p3 : select_ln256_2_fu_1128_p3);

assign select_ln890_9_fu_1186_p3 = ((and_ln890_9_fu_1142_p2[0:0] == 1'b1) ? select_ln890_7_fu_1066_p3 : select_ln256_3_fu_1178_p3);

assign select_ln890_fu_590_p3 = ((and_ln890_fu_554_p2[0:0] == 1'b1) ? zext_ln238_fu_468_p1 : select_ln886_fu_582_p3);

assign sub_ln213_10_fu_856_p2 = (zext_ln213_2_fu_852_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_11_fu_862_p2 = (zext_ln208_fu_464_p1 - zext_ln213_2_fu_852_p1);

assign sub_ln213_12_fu_970_p2 = (t1_V_fu_472_p3 - zext_ln213_8_fu_966_p1);

assign sub_ln213_13_fu_1088_p2 = (or_ln213_1_fu_1080_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_14_fu_1216_p2 = (zext_ln208_fu_464_p1 - zext_ln213_9_fu_1206_p1);

assign sub_ln213_15_fu_1324_p2 = (t1_V_fu_472_p3 - zext_ln213_10_fu_1320_p1);

assign sub_ln213_16_fu_1442_p2 = (or_ln213_2_fu_1434_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_17_fu_1570_p2 = (zext_ln208_fu_464_p1 - zext_ln213_3_fu_1560_p1);

assign sub_ln213_18_fu_1678_p2 = (t1_V_fu_472_p3 - zext_ln213_11_fu_1674_p1);

assign sub_ln213_19_fu_1770_p2 = (or_ln213_3_fu_1762_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_1_fu_506_p2 = (zext_ln208_fu_464_p1 - zext_ln213_fu_496_p1);

assign sub_ln213_20_fu_1872_p2 = (zext_ln208_fu_464_p1 - zext_ln213_4_fu_1862_p1);

assign sub_ln213_21_fu_1954_p2 = (t1_V_fu_472_p3 - zext_ln213_12_fu_1950_p1);

assign sub_ln213_22_fu_2046_p2 = (or_ln213_4_fu_2038_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_23_fu_2148_p2 = (zext_ln208_fu_464_p1 - zext_ln213_5_fu_2138_p1);

assign sub_ln213_24_fu_2230_p2 = (t1_V_fu_472_p3 - zext_ln213_13_fu_2226_p1);

assign sub_ln213_25_fu_2322_p2 = (or_ln213_5_fu_2314_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_26_fu_2424_p2 = (zext_ln208_fu_464_p1 - zext_ln213_6_fu_2414_p1);

assign sub_ln213_27_fu_2506_p2 = (t1_V_fu_472_p3 - zext_ln213_14_fu_2502_p1);

assign sub_ln213_28_fu_2598_p2 = (or_ln213_6_fu_2590_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_29_fu_2700_p2 = (zext_ln208_fu_464_p1 - zext_ln213_7_fu_2690_p1);

assign sub_ln213_2_fu_1210_p2 = (zext_ln213_9_fu_1206_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_30_fu_2782_p2 = (t1_V_fu_472_p3 - zext_ln213_15_fu_2778_p1);

assign sub_ln213_31_fu_2874_p2 = (or_ln213_7_fu_2866_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_3_fu_1564_p2 = (zext_ln213_3_fu_1560_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_4_fu_1866_p2 = (zext_ln213_4_fu_1862_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_5_fu_2142_p2 = (zext_ln213_5_fu_2138_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_6_fu_2418_p2 = (zext_ln213_6_fu_2414_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_7_fu_2694_p2 = (zext_ln213_7_fu_2690_p1 - zext_ln208_fu_464_p1);

assign sub_ln213_8_fu_612_p2 = (t1_V_fu_472_p3 - zext_ln213_1_fu_608_p1);

assign sub_ln213_9_fu_730_p2 = (or_ln_fu_722_p3 - zext_ln208_fu_464_p1);

assign sub_ln213_fu_500_p2 = (zext_ln213_fu_496_p1 - zext_ln208_fu_464_p1);

assign t1_V_fu_472_p3 = {{1'd1}, {p_read30_int_reg}};

assign x_cast_fu_3249_p1 = x_read_reg_3422_pp0_iter1_reg;

assign xor_ln243_1_fu_888_p2 = (icmp_ln243_1_fu_882_p2 ^ 1'd1);

assign xor_ln243_2_fu_1242_p2 = (icmp_ln243_2_fu_1236_p2 ^ 1'd1);

assign xor_ln243_3_fu_1596_p2 = (icmp_ln243_3_fu_1590_p2 ^ 1'd1);

assign xor_ln243_4_fu_1898_p2 = (icmp_ln243_4_fu_1892_p2 ^ 1'd1);

assign xor_ln243_5_fu_2174_p2 = (icmp_ln243_5_fu_2168_p2 ^ 1'd1);

assign xor_ln243_6_fu_2450_p2 = (icmp_ln243_6_fu_2444_p2 ^ 1'd1);

assign xor_ln243_7_fu_2726_p2 = (icmp_ln243_7_fu_2720_p2 ^ 1'd1);

assign xor_ln243_fu_532_p2 = (icmp_ln243_fu_526_p2 ^ 1'd1);

assign xor_ln250_1_fu_988_p2 = (icmp_ln250_1_fu_982_p2 ^ 1'd1);

assign xor_ln250_2_fu_1342_p2 = (icmp_ln250_2_fu_1336_p2 ^ 1'd1);

assign xor_ln250_3_fu_1696_p2 = (icmp_ln250_3_fu_1690_p2 ^ 1'd1);

assign xor_ln250_4_fu_1972_p2 = (icmp_ln250_4_fu_1966_p2 ^ 1'd1);

assign xor_ln250_5_fu_2248_p2 = (icmp_ln250_5_fu_2242_p2 ^ 1'd1);

assign xor_ln250_6_fu_2524_p2 = (icmp_ln250_6_fu_2518_p2 ^ 1'd1);

assign xor_ln250_7_fu_2800_p2 = (icmp_ln250_7_fu_2794_p2 ^ 1'd1);

assign xor_ln250_fu_630_p2 = (icmp_ln250_fu_624_p2 ^ 1'd1);

assign xor_ln256_1_fu_1136_p2 = (icmp_ln256_1_fu_1074_p2 ^ 1'd1);

assign xor_ln256_2_fu_1490_p2 = (icmp_ln256_2_fu_1428_p2 ^ 1'd1);

assign xor_ln256_3_fu_1808_p2 = (icmp_ln256_3_fu_1756_p2 ^ 1'd1);

assign xor_ln256_4_fu_2084_p2 = (icmp_ln256_4_fu_2032_p2 ^ 1'd1);

assign xor_ln256_5_fu_2360_p2 = (icmp_ln256_5_fu_2308_p2 ^ 1'd1);

assign xor_ln256_6_fu_2636_p2 = (icmp_ln256_6_fu_2584_p2 ^ 1'd1);

assign xor_ln256_7_fu_2912_p2 = (icmp_ln256_7_fu_2860_p2 ^ 1'd1);

assign xor_ln256_fu_778_p2 = (icmp_ln256_fu_716_p2 ^ 1'd1);

assign xor_ln257_1_fu_1106_p2 = (icmp_ln257_1_fu_1100_p2 ^ 1'd1);

assign xor_ln257_2_fu_1460_p2 = (icmp_ln257_2_fu_1454_p2 ^ 1'd1);

assign xor_ln257_3_fu_1788_p2 = (icmp_ln257_3_fu_1782_p2 ^ 1'd1);

assign xor_ln257_4_fu_2064_p2 = (icmp_ln257_4_fu_2058_p2 ^ 1'd1);

assign xor_ln257_5_fu_2340_p2 = (icmp_ln257_5_fu_2334_p2 ^ 1'd1);

assign xor_ln257_6_fu_2616_p2 = (icmp_ln257_6_fu_2610_p2 ^ 1'd1);

assign xor_ln257_7_fu_2892_p2 = (icmp_ln257_7_fu_2886_p2 ^ 1'd1);

assign xor_ln257_fu_748_p2 = (icmp_ln257_fu_742_p2 ^ 1'd1);

assign xor_ln886_10_fu_2180_p2 = (icmp_ln886_29_fu_2126_p2 ^ 1'd1);

assign xor_ln886_11_fu_2270_p2 = (icmp_ln886_30_fu_2220_p2 ^ 1'd1);

assign xor_ln886_12_fu_2456_p2 = (icmp_ln886_31_fu_2402_p2 ^ 1'd1);

assign xor_ln886_13_fu_2546_p2 = (icmp_ln886_32_fu_2496_p2 ^ 1'd1);

assign xor_ln886_14_fu_2732_p2 = (icmp_ln886_33_fu_2678_p2 ^ 1'd1);

assign xor_ln886_15_fu_2822_p2 = (icmp_ln886_34_fu_2772_p2 ^ 1'd1);

assign xor_ln886_1_fu_662_p2 = (icmp_ln886_20_fu_602_p2 ^ 1'd1);

assign xor_ln886_2_fu_904_p2 = (icmp_ln886_21_fu_840_p2 ^ 1'd1);

assign xor_ln886_3_fu_1020_p2 = (icmp_ln886_22_fu_960_p2 ^ 1'd1);

assign xor_ln886_4_fu_1258_p2 = (icmp_ln886_23_fu_1194_p2 ^ 1'd1);

assign xor_ln886_5_fu_1374_p2 = (icmp_ln886_24_fu_1314_p2 ^ 1'd1);

assign xor_ln886_6_fu_1612_p2 = (icmp_ln886_25_fu_1548_p2 ^ 1'd1);

assign xor_ln886_7_fu_1718_p2 = (icmp_ln886_26_fu_1668_p2 ^ 1'd1);

assign xor_ln886_8_fu_1904_p2 = (icmp_ln886_27_fu_1850_p2 ^ 1'd1);

assign xor_ln886_9_fu_1994_p2 = (icmp_ln886_28_fu_1944_p2 ^ 1'd1);

assign xor_ln886_fu_548_p2 = (icmp_ln886_fu_484_p2 ^ 1'd1);

assign xor_ln890_1_fu_916_p2 = (xor_ln886_2_fu_904_p2 ^ and_ln890_5_fu_910_p2);

assign xor_ln890_2_fu_1270_p2 = (xor_ln886_4_fu_1258_p2 ^ and_ln890_11_fu_1264_p2);

assign xor_ln890_3_fu_1624_p2 = (xor_ln886_6_fu_1612_p2 ^ and_ln890_17_fu_1618_p2);

assign xor_ln890_4_fu_1916_p2 = (xor_ln886_8_fu_1904_p2 ^ and_ln890_23_fu_1910_p2);

assign xor_ln890_5_fu_2192_p2 = (xor_ln886_10_fu_2180_p2 ^ and_ln890_29_fu_2186_p2);

assign xor_ln890_6_fu_2468_p2 = (xor_ln886_12_fu_2456_p2 ^ and_ln890_35_fu_2462_p2);

assign xor_ln890_7_fu_2744_p2 = (xor_ln886_14_fu_2732_p2 ^ and_ln890_41_fu_2738_p2);

assign xor_ln890_fu_560_p2 = (xor_ln886_fu_548_p2 ^ and_ln890_fu_554_p2);

assign zext_ln208_10_fu_1118_p1 = p_read40_int_reg;

assign zext_ln208_11_fu_1248_p1 = p_read24_int_reg;

assign zext_ln208_12_fu_1356_p1 = p_read7_int_reg;

assign zext_ln208_13_fu_1472_p1 = p_read41_int_reg;

assign zext_ln208_14_fu_3022_p1 = p_read88_reg_3497;

assign zext_ln208_15_fu_3042_p1 = p_read_12_reg_3447;

assign zext_ln208_16_fu_3088_p1 = p_read99_reg_3492;

assign zext_ln208_17_fu_3111_p1 = p_read_11_reg_3442;

assign zext_ln208_18_fu_3157_p1 = p_read1010_reg_3487;

assign zext_ln208_19_fu_3180_p1 = p_read_10_reg_3437;

assign zext_ln208_1_fu_538_p1 = p_read22_int_reg;

assign zext_ln208_20_fu_3226_p1 = p_read_42_reg_3482;

assign zext_ln208_21_fu_3252_p1 = p_read_9_reg_3432_pp0_iter1_reg;

assign zext_ln208_22_fu_3295_p1 = p_read_41_reg_3477_pp0_iter1_reg;

assign zext_ln208_23_fu_3318_p1 = p_read_8_reg_3427_pp0_iter1_reg;

assign zext_ln208_24_fu_760_p1 = p_read39_int_reg;

assign zext_ln208_25_fu_2964_p1 = add_ln208_24_fu_2958_p2;

assign zext_ln208_26_fu_2974_p1 = add_ln208_25_fu_2968_p2;

assign zext_ln208_27_fu_2990_p1 = add_ln208_27_fu_2984_p2;

assign zext_ln208_28_fu_3000_p1 = add_ln208_28_fu_2994_p2;

assign zext_ln208_2_fu_644_p1 = p_read5_int_reg;

assign zext_ln208_3_fu_1602_p1 = p_read25_int_reg;

assign zext_ln208_4_fu_3065_p1 = p_read_28_reg_3472;

assign zext_ln208_5_fu_3134_p1 = p_read_27_reg_3467;

assign zext_ln208_6_fu_3203_p1 = p_read_26_reg_3462;

assign zext_ln208_7_fu_3272_p1 = p_read_25_reg_3457_pp0_iter1_reg;

assign zext_ln208_8_fu_894_p1 = p_read23_int_reg;

assign zext_ln208_9_fu_1002_p1 = p_read6_int_reg;

assign zext_ln208_fu_464_p1 = p_read30_int_reg;

assign zext_ln213_10_fu_1320_p1 = p_read15_int_reg;

assign zext_ln213_11_fu_1674_p1 = p_read16_int_reg;

assign zext_ln213_12_fu_1950_p1 = p_read17_int_reg;

assign zext_ln213_13_fu_2226_p1 = p_read18_int_reg;

assign zext_ln213_14_fu_2502_p1 = p_read19_int_reg;

assign zext_ln213_15_fu_2778_p1 = p_read20_int_reg;

assign zext_ln213_1_fu_608_p1 = p_read13_int_reg;

assign zext_ln213_2_fu_852_p1 = p_read32_int_reg;

assign zext_ln213_3_fu_1560_p1 = p_read34_int_reg;

assign zext_ln213_4_fu_1862_p1 = p_read35_int_reg;

assign zext_ln213_5_fu_2138_p1 = p_read36_int_reg;

assign zext_ln213_6_fu_2414_p1 = p_read37_int_reg;

assign zext_ln213_7_fu_2690_p1 = p_read38_int_reg;

assign zext_ln213_8_fu_966_p1 = p_read14_int_reg;

assign zext_ln213_9_fu_1206_p1 = p_read33_int_reg;

assign zext_ln213_fu_496_p1 = p_read31_int_reg;

assign zext_ln238_fu_468_p1 = p_read21_int_reg;

assign zext_ln256_1_fu_1156_p1 = select_ln890_8_fu_1148_p3;

assign zext_ln256_2_fu_1510_p1 = select_ln890_13_fu_1502_p3;

assign zext_ln256_3_fu_1828_p1 = select_ln890_18_fu_1820_p3;

assign zext_ln256_4_fu_2104_p1 = select_ln890_23_fu_2096_p3;

assign zext_ln256_5_fu_2380_p1 = select_ln890_28_fu_2372_p3;

assign zext_ln256_6_fu_2656_p1 = select_ln890_33_fu_2648_p3;

assign zext_ln256_7_fu_2932_p1 = select_ln890_38_fu_2924_p3;

assign zext_ln256_8_fu_2954_p1 = and_ln890_46_fu_2948_p2;

assign zext_ln256_fu_798_p1 = select_ln890_3_fu_790_p3;

assign zext_ln886_10_fu_2750_p1 = xor_ln890_7_fu_2744_p2;

assign zext_ln886_1_fu_566_p1 = xor_ln890_fu_560_p2;

assign zext_ln886_2_fu_598_p1 = select_ln890_fu_590_p3;

assign zext_ln886_3_fu_836_p1 = select_ln890_4_fu_828_p3;

assign zext_ln886_4_fu_922_p1 = xor_ln890_1_fu_916_p2;

assign zext_ln886_5_fu_1276_p1 = xor_ln890_2_fu_1270_p2;

assign zext_ln886_6_fu_1630_p1 = xor_ln890_3_fu_1624_p2;

assign zext_ln886_7_fu_1922_p1 = xor_ln890_4_fu_1916_p2;

assign zext_ln886_8_fu_2198_p1 = xor_ln890_5_fu_2192_p2;

assign zext_ln886_9_fu_2474_p1 = xor_ln890_6_fu_2468_p2;

assign zext_ln886_fu_480_p1 = hit_dt_int_reg;

always @ (posedge ap_clk) begin
    ap_return_0_int_reg[4:2] <= 3'b000;
end

endmodule //hcal_cluster_hls_Find_cluster
